# Generated by Django 4.2 on 2024-04-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirementset',
            old_name='name',
            new_name='display_name',
        ),
    ]
