# Generated by Django 4.2 on 2024-04-16 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_rename_name_requirementset_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='obligation_level',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='parent_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='requirements.requirement'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='rationale',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='statement',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='verification_class',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
