# Generated by Django 4.2 on 2024-04-17 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_requirement_obligation_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='requirement_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='requirements.requirementset'),
        ),
    ]
