# Generated by Django 4.2 on 2024-04-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0004_alter_requirement_requirement_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
