# Generated by Django 4.2 on 2024-04-20 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_notification_user'),
        ('requirements', '0005_requirement_state_requirement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='quality_assurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile'),
        ),
    ]
