# Generated by Django 4.2 on 2024-04-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0046_alter_document_errata_alter_document_revision_notes'),
        ('requirements', '0006_requirement_quality_assurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='reference_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.reference_list'),
        ),
    ]
