# Generated by Django 4.2 on 2024-04-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0007_requirement_reference_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='verification_method',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='verification_results',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
