# Generated by Django 4.2 on 2024-04-22 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0008_requirement_verification_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='parent_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='requirements.requirement'),
        ),
    ]
