# Generated by Django 4.2.11 on 2024-06-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0010_requirement_derived_from_requirement_satisfied_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='derived_from',
        ),
        migrations.AddField(
            model_name='requirement',
            name='derived_from',
            field=models.ManyToManyField(blank=True, related_name='derived_requirements', to='requirements.requirement'),
        ),
    ]
