# Generated by Django 4.2.11 on 2024-07-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0011_remove_requirement_derived_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='requirementset',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
