# Generated by Django 4.2.11 on 2024-07-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0012_requirement_tags_requirementset_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
