# Generated by Django 4.2.11 on 2024-09-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0015_rename_tags_requirement_old_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='requirements_tags', to='projects.tag'),
        ),
    ]
