# Generated by Django 4.2.11 on 2024-09-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_task_tags'),
        ('requirements', '0017_auto_20240913_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementset',
            name='tags',
        ),
        migrations.AddField(
            model_name='requirementset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='requirement_sets_tags', to='projects.tag'),
        ),
    ]
