# Generated by Django 4.2.11 on 2024-11-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0018_remove_requirementset_tags_requirementset_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='satisfied_by',
        ),
        migrations.AddField(
            model_name='requirement',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_requirements', to='requirements.requirement'),
        ),
    ]
