# Generated by Django 4.2.11 on 2026-06-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0019_remove_requirement_satisfied_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='external_requirement_id',
            field=models.CharField(blank=True, default='', help_text='External requirement identifier from customer or third-party specification systems.', max_length=255, null=True),
        ),
    ]
