# Generated by Django 4.2.11 on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0066_document_reference"),
        ("requirements", "0020_requirement_external_requirement_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="statement_references",
            field=models.ManyToManyField(
                blank=True,
                related_name="requirements",
                to="documents.document_reference",
            ),
        ),
    ]
