# Generated by Django 4.2.11 on 2026-06-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0021_requirement_statement_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='reference_list',
        ),
    ]
