# Generated by Django 4.2.11 on 2026-06-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0067_alter_document_reference_id'),
        ('requirements', '0022_remove_requirement_reference_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='verification_references',
            field=models.ManyToManyField(blank=True, help_text='Document references used as verification evidence for this requirement.', related_name='verification_requirements', to='documents.document_reference'),
        ),
    ]
