# Generated by Django 4.2.11 on 2026-06-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0023_requirement_verification_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementset',
            name='created_by_is_visible',
            field=models.BooleanField(default=True, help_text='Show the created by field.'),
        ),
        migrations.AddField(
            model_name='requirementset',
            name='derived_from_is_enabled',
            field=models.BooleanField(default=True, help_text='Show the derived from field.'),
        ),
        migrations.AddField(
            model_name='requirementset',
            name='external_requirement_id_is_enabled',
            field=models.BooleanField(default=True, help_text='Show the external ID field.'),
        ),
        migrations.AddField(
            model_name='requirementset',
            name='hierarchical_requirements_is_enabled',
            field=models.BooleanField(default=True, help_text='Show the parent requirement field.'),
        ),
        migrations.AddField(
            model_name='requirementset',
            name='requirement_type_is_enabled',
            field=models.BooleanField(default=True, help_text='Show the requirement type field.'),
        ),
        migrations.AddField(
            model_name='requirementset',
            name='superseded_by_is_enabled',
            field=models.BooleanField(default=True, help_text='Show the superseded by field.'),
        ),
        migrations.AddField(
            model_name='requirementset',
            name='verification_class_is_enabled',
            field=models.BooleanField(default=True, help_text='Show the verification class field.'),
        ),
        migrations.AddField(
            model_name='requirementset',
            name='verification_method_markdown_is_enabled',
            field=models.BooleanField(default=True, help_text='Show the verification method field.'),
        ),
        migrations.AddField(
            model_name='requirementset',
            name='verification_results_markdown_is_enabled',
            field=models.BooleanField(default=True, help_text='Show the verification results field.'),
        ),
    ]
