# Generated by Django 4.2 on 2023-11-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_file_file_alter_image_file'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='files',
            field=models.ManyToManyField(blank=True, to='files.file'),
        ),
    ]
