# Generated by Django 4.2 on 2024-03-17 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0044_assembly_currency'),
        ('parts', '0074_migrate_parttypes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pcbas', '0047_pcba_currency_pcba_price'),
        ('purchasing', '0003_purchaseorder_incoterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12)),
                ('minimum_order_quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('is_latest_price', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='assemblies.assembly')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='parts.part')),
                ('pcba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pcbas.pcba')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.supplier')),
            ],
        ),
    ]
