# Generated by Django 4.2 on 2024-05-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_image_project'),
        ('purchasing', '0005_price_migration_to_new_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image'),
        ),
    ]
