# Generated by Django 4.2 on 2024-05-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_supplier_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='default_currency',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
