# Generated by Django 4.2.11 on 2024-07-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0007_supplier_default_currency_alter_supplier_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
