# Generated by Django 4.2.11 on 2024-07-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0009_poitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='temporary_manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poitem',
            name='temporary_mpn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
