# Generated by Django 4.2.11 on 2024-07-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0010_poitem_temporary_manufacturer_poitem_temporary_mpn'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
