# Generated by Django 4.2.11 on 2024-07-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0012_purchaseorder_freight_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='po_currency',
            field=models.CharField(blank=True, null=True),
        ),
    ]
