# Generated by Django 4.2.11 on 2024-08-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_testdata_status'),
        ('purchasing', '0015_purchaseorder_billing_address_purchaseorder_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.lot'),
        ),
    ]
