# Generated by Django 4.2.11 on 2024-08-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0016_purchaseorder_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='default_payment_terms',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='default_shipping_terms',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
