# Generated by Django 4.2.11 on 2024-08-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0017_supplier_default_payment_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='designator',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
