# Generated by Django 4.2.11 on 2024-09-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_task_tags'),
        ('purchasing', '0018_poitem_designator'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='po_tags', to='projects.tag'),
        ),
    ]
