# Generated by Django 4.2.11 on 2024-09-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0019_purchaseorder_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='item_received',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
