# Generated by Django 4.2.11 on 2024-09-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0020_poitem_item_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='default_vat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
