# Generated by Django 4.2.11 on 2024-12-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0021_supplier_default_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='quantity_received',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
