# Generated by Django 4.2.11 on 2025-11-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0022_poitem_quantity_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='nexar_seller_id',
            field=models.IntegerField(blank=True, help_text='Nexar seller ID from the Octopart API (e.g., 459 for DigiKey)', null=True),
        ),
    ]
