# Generated by Django 4.2 on 2023-09-18 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0063_part_part_information_part_price_history_part_stock_and_more'),
        ('assemblies', '0035_assembly_released_date'),
        ('files', '0008_alter_file_file_alter_image_file'),
        ('pcbas', '0038_pcba_bom_parts'),
        ('production', '0002_production_file_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_archived', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='production',
            name='asm_serial_id',
        ),
        migrations.RemoveField(
            model_name='production',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='production',
            name='linked_assemblies',
        ),
        migrations.RemoveField(
            model_name='production',
            name='linked_pcbas',
        ),
        migrations.RemoveField(
            model_name='production',
            name='next_prod',
        ),
        migrations.RemoveField(
            model_name='production',
            name='pcba_part_number',
        ),
        migrations.RemoveField(
            model_name='production',
            name='prev_prod',
        ),
        migrations.RemoveField(
            model_name='production',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='production',
            name='sub_production',
        ),
        migrations.AddField(
            model_name='production',
            name='assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='assemblies.assembly'),
        ),
        migrations.AddField(
            model_name='production',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='production',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='parts.part'),
        ),
        migrations.AddField(
            model_name='production',
            name='pcba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='pcbas.pcba'),
        ),
        migrations.AlterField(
            model_name='production',
            name='comment',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_data', models.JSONField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_archived', models.BooleanField(blank=True, default=False)),
                ('files', models.ManyToManyField(related_name='test_data', to='files.file')),
                ('produced_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='production.production')),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_items', to='production.lot'),
        ),
    ]
