# Generated by Django 4.2 on 2024-05-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_image_project'),
        ('production', '0005_alter_testdata_options_testdata_step_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='test_data', to='files.file'),
        ),
    ]
