# Generated by Django 4.2 on 2024-05-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_testdata_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
