# Generated by Django 4.2.11 on 2024-09-02 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0080_part_minimum_stock_level'),
        ('assemblies', '0049_assembly_minimum_stock_level'),
        ('pcbas', '0053_pcba_minimum_stock_level'),
        ('documents', '0048_markdowntext'),
        ('production', '0007_testdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_item_assembly', to='assemblies.assembly'),
        ),
        migrations.AddField(
            model_name='lot',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.markdowntext'),
        ),
        migrations.AddField(
            model_name='lot',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_item_part', to='parts.part'),
        ),
        migrations.AddField(
            model_name='lot',
            name='pcba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_item_pcba', to='pcbas.pcba'),
        ),
        migrations.AddField(
            model_name='lot',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
