# Generated by Django 4.2.11 on 2024-09-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0048_markdowntext'),
        ('production', '0008_lot_assembly_lot_description_lot_part_lot_pcba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.markdowntext'),
        ),
    ]
