# Generated by Django 4.2.11 on 2024-09-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_production_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='planned_production_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='serial_number_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
