# Generated by Django 4.2.11 on 2024-11-12 20:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_lot_planned_production_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurements_x', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('measurements_y', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('x_unit', models.CharField(blank=True, max_length=150)),
                ('y_unit', models.CharField(blank=True, max_length=150)),
                ('upper_limit', models.FloatField(blank=True, null=True)),
                ('lower_limit', models.FloatField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('step_title', models.CharField(blank=True, max_length=500)),
                ('step_group', models.CharField(blank=True, max_length=500)),
                ('production_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vector_measurements', to='production.production')),
            ],
        ),
        migrations.CreateModel(
            name='ScalarMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('upper_limit', models.FloatField(blank=True, null=True)),
                ('lower_limit', models.FloatField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('step_title', models.CharField(blank=True, max_length=500)),
                ('step_group', models.CharField(blank=True, max_length=500)),
                ('production_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scalar_measurements', to='production.production')),
            ],
        ),
        migrations.AddField(
            model_name='testdata',
            name='ScalarMeasurement',
            field=models.ManyToManyField(blank=True, null=True, related_name='tests', to='production.scalarmeasurement'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='VectorMeasurement',
            field=models.ManyToManyField(blank=True, null=True, related_name='tests', to='production.vectormeasurement'),
        ),
    ]
