# Generated by Django 4.1.5 on 2023-02-10 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('timetracking', '0001_initial'), ('timetracking', '0002_auto_20200410_2052'), ('timetracking', '0003_auto_20200410_2132'), ('timetracking', '0004_auto_20200528_1452'), ('timetracking', '0005_auto_20200729_1800'), ('timetracking', '0006_employeetime_task_id')]

    initial = True

    dependencies = [
        ('projects', '0026_project_is_active'),
        ('projects', '0004_remove_project_project_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('stop_time', models.TimeField(blank=True, null=True)),
                ('hour', models.CharField(blank=True, max_length=5, null=True)),
                ('comment', models.TextField(blank=True, max_length=200)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.task')),
            ],
        ),
    ]
