# Generated by Django 3.0.4 on 2020-04-10 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_project_contact'),
        ('timetracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetime',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
