# Generated by Django 3.0.4 on 2020-04-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0002_auto_20200410_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetime',
            name='hour',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
