# Generated by Django 3.0.4 on 2020-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0003_auto_20200410_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetime',
            name='hour',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
