# Generated by Django 3.0.4 on 2020-07-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0004_auto_20200528_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetime',
            name='hour',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
