# Generated by Django 3.2.15 on 2022-12-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_project_is_active'),
        ('timetracking', '0005_auto_20200729_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetime',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.task'),
        ),
    ]
