# Generated by Django 4.1.5 on 2023-02-10 11:14

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('assemblies', '0001_initial'), ('assemblies', '0002_auto_20200505_2131'), ('assemblies', '0003_auto_20200506_1744'), ('assemblies', '0004_auto_20200506_1816'), ('assemblies', '0005_auto_20200506_1857'), ('assemblies', '0006_auto_20200516_1733'), ('assemblies', '0007_auto_20200516_1736'), ('assemblies', '0008_auto_20200516_1800'), ('assemblies', '0009_auto_20200518_1027'), ('assemblies', '0010_auto_20200707_2102'), ('assemblies', '0011_auto_20200707_2215'), ('assemblies', '0012_auto_20200711_2356'), ('assemblies', '0013_assembly_last_updated'), ('assemblies', '0014_auto_20200726_1637'), ('assemblies', '0015_assembly_constructed'), ('assemblies', '0016_auto_20211203_1224'), ('assemblies', '0017_remove_assembly_ids_used_for_blueprint'), ('assemblies', '0015_assembly_allow_alternate'), ('assemblies', '0018_merge_20220217_1223'), ('assemblies', '0019_remove_assembly_allow_alternate'), ('assemblies', '0020_assembly_revision_notes'), ('assemblies', '0021_auto_20220324_0908'), ('assemblies', '0022_assembly_bom_id'), ('assemblies', '0023_assembly_multiple_bom_vars'), ('assemblies', '0024_assembly_errata'), ('assemblies', '0025_assembly_reference_list_id'), ('assemblies', '0026_auto_20220819_0838'), ('assemblies', '0027_auto_20220915_1704'), ('assemblies', '0028_assembly_generic_file_ids'), ('assemblies', '0029_assembly_project'), ('assemblies', '0030_assembly_generic_files_used'), ('assemblies', '0031_assembly_is_latest_revision'), ('assemblies', '0032_assembly_is_archived'), ('assemblies', '0033_assembly_archived_date'), ('assemblies', '0034_assembly_full_part_number')]

    initial = True

    dependencies = [
        ('parts', '0005_part_part_type'),
        ('parts', '0007_part_price_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0020_project_archived_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField()),
                ('top_level_assembly', models.CharField(blank=True, max_length=5)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('release_state', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12)),
                ('revision', models.CharField(max_length=2)),
                ('model_url', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assembly_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), default=list, null=True, size=None)),
                ('part_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), default=list, null=True, size=None)),
                ('assembly_refdes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), default=list, null=True, size=None)),
                ('part_refdes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), default=list, null=True, size=None)),
                ('pcba_refdes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), default=list, null=True, size=None)),
                ('pcba_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), default=list, null=True, size=None)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('graph_blueprint', models.BooleanField(default=False)),
                ('revision_notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('bom_id', models.IntegerField(blank=True, null=True)),
                ('multiple_bom_vars', models.BooleanField(blank=True, default=False)),
                ('errata', models.CharField(blank=True, max_length=1000, null=True)),
                ('reference_list_id', models.IntegerField(blank=True, default=-1)),
                ('archived', models.IntegerField(blank=True, default=0)),
                ('notes_for_next_revision', models.CharField(blank=True, max_length=1000, null=True)),
                ('assembly_drawing', models.IntegerField(blank=True, default=-1)),
                ('assembly_drawing_raw', models.IntegerField(blank=True, default=-1)),
                ('generic_file_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0), blank=True, default=list, size=None)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('generic_files_used', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0), blank=True, default=list, size=None)),
                ('is_latest_revision', models.BooleanField(blank=True, default=False)),
                ('is_archived', models.BooleanField(blank=True, default=False)),
                ('archived_date', models.DateField(blank=True, null=True)),
                ('full_part_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
