# Generated by Django 3.0.4 on 2020-05-05 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0005_part_part_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField()),
                ('top_level_assembly', models.CharField(blank=True, max_length=5)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('release_state', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12)),
                ('revision', models.CharField(max_length=2)),
                ('model_url', models.CharField(blank=True, max_length=200)),
                ('production_status', models.CharField(blank=True, max_length=20)),
                ('assembly_used', models.ManyToManyField(related_name='_assembly_assembly_used_+', to='assemblies.Assembly')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part_used', models.ManyToManyField(to='parts.Part')),
            ],
        ),
    ]
