# Generated by Django 3.0.4 on 2020-05-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_part_part_type'),
        ('assemblies', '0002_auto_20200505_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='part_used',
            field=models.ManyToManyField(blank=True, to='parts.Part'),
        ),
    ]
