# Generated by Django 3.0.4 on 2020-05-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_part_part_type'),
        ('assemblies', '0003_auto_20200506_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='part_used',
            field=models.ManyToManyField(to='parts.Part'),
        ),
    ]
