# Generated by Django 3.0.4 on 2020-05-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0005_auto_20200506_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='assembly_used',
        ),
        migrations.AddField(
            model_name='assembly',
            name='assembly_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='part_used',
        ),
        migrations.AddField(
            model_name='assembly',
            name='part_used',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
