# Generated by Django 3.0.4 on 2020-05-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_part_price_qty'),
        ('assemblies', '0007_auto_20200516_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='assembly_used',
        ),
        migrations.AddField(
            model_name='assembly',
            name='assembly_used',
            field=models.ManyToManyField(blank=True, related_name='_assembly_assembly_used_+', to='assemblies.Assembly'),
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='part_used',
        ),
        migrations.AddField(
            model_name='assembly',
            name='part_used',
            field=models.ManyToManyField(to='parts.Part'),
        ),
    ]
