# Generated by Django 3.0.4 on 2020-07-07 20:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0010_auto_20200707_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='assembly_refdes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='assembly',
            name='part_refdes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='assembly_used',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='part_used',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), default=list, null=True, size=None),
        ),
    ]
