# Generated by Django 3.0.4 on 2020-07-11 21:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0011_auto_20200707_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='pcba_refdes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='assembly',
            name='pcba_used',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), default=list, null=True, size=None),
        ),
    ]
