# Generated by Django 3.0.4 on 2020-07-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0012_auto_20200711_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
