# Generated by Django 3.0.4 on 2022-01-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0014_auto_20200726_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='allow_alternate',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
