# Generated by Django 3.0.4 on 2021-12-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0014_auto_20200726_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='constructed',
            field=models.BooleanField(default=False),
        ),
    ]
