# Generated by Django 3.0.4 on 2021-12-03 11:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0015_assembly_constructed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assembly',
            old_name='constructed',
            new_name='graph_blueprint',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='production_status',
        ),
        migrations.AddField(
            model_name='assembly',
            name='ids_used_for_blueprint',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
