# Generated by Django 3.0.4 on 2021-12-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0016_auto_20211203_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='ids_used_for_blueprint',
        ),
    ]
