# Generated by Django 3.0.4 on 2022-02-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0017_remove_assembly_ids_used_for_blueprint'),
        ('assemblies', '0015_assembly_allow_alternate'),
    ]

    operations = [
    ]
