# Generated by Django 3.0.4 on 2022-02-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0018_merge_20220217_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='allow_alternate',
        ),
    ]
