# Generated by Django 3.0.4 on 2022-03-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0019_remove_assembly_allow_alternate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='revision_notes',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
