# Generated by Django 3.0.4 on 2022-03-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0020_assembly_revision_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='revision_notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
