# Generated by Django 3.0.4 on 2022-05-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0022_assembly_bom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='multiple_bom_vars',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
