# Generated by Django 3.0.4 on 2022-07-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0023_assembly_multiple_bom_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='errata',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
