# Generated by Django 3.0.4 on 2022-07-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0024_assembly_errata'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='reference_list_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
