# Generated by Django 3.0.4 on 2022-08-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0025_assembly_reference_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='archived',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='assembly',
            name='notes_for_next_revision',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
