# Generated by Django 3.2.15 on 2022-09-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0026_auto_20220819_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='assembly_drawing',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='assembly',
            name='assembly_drawing_raw',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
