# Generated by Django 3.2.15 on 2022-09-16 10:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0027_auto_20220915_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='generic_file_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0), blank=True, default=list, size=None),
        ),
    ]
