# Generated by Django 3.2.15 on 2023-01-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0030_assembly_generic_files_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='is_latest_revision',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
