# Generated by Django 4.1.5 on 2023-01-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0033_assembly_archived_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='full_part_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
