# Generated by Django 4.2 on 2023-04-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0001_squashed_0034_assembly_full_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='released_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
