# Generated by Django 4.2 on 2023-11-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_file_file_alter_image_file'),
        ('assemblies', '0035_assembly_released_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='files',
            field=models.ManyToManyField(blank=True, to='files.file'),
        ),
    ]
