# Generated by Django 4.2 on 2023-11-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0037_migrate_legacy_file_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='serial_number_counter',
            field=models.IntegerField(default=0),
        ),
    ]
