# Generated by Django 4.2 on 2024-02-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0040_assembly_quality_assurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='assembly_refdes',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='assembly_used',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='multiple_bom_vars',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='part_refdes',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='part_used',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='pcba_refdes',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='pcba_used',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='top_level_assembly',
        ),
    ]
