# Generated by Django 4.2.11 on 2024-06-08 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0048_markdowntext'),
        ('assemblies', '0045_alter_assembly_errata_alter_assembly_revision_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='markdown_notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.markdowntext'),
        ),
    ]
