# Generated by Django 4.2.11 on 2024-08-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0046_assembly_markdown_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='external_part_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
