# Generated by Django 4.2.11 on 2024-08-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0047_assembly_external_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='current_total_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
