# Generated by Django 4.2.11 on 2024-09-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_task_tags'),
        ('assemblies', '0049_assembly_minimum_stock_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assemblies_tags', to='projects.tag'),
        ),
    ]
