# Generated by Django 4.2.11 on 2025-10-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0051_assembly_markdown_note_tabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='revision',
            field=models.CharField(max_length=10),
        ),
    ]
