# Generated by Django 4.2.11 on 2025-11-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0054_populate_revision_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='formatted_revision',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
