# Generated by Django 4.2.11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0094_parttype_applies_to'),
        ('assemblies', '0056_populate_formatted_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='part_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='parts.parttype'
            ),
        ),
    ]
