# Generated by Django 4.2.11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assemblies', '0057_assembly_part_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_by', to='assemblies.assembly')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_assemblies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='starredassembly',
            index=models.Index(fields=['user'], name='assemblies_s_user_idx'),
        ),
        migrations.AddIndex(
            model_name='starredassembly',
            index=models.Index(fields=['assembly'], name='assemblies_s_assembly_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='starredassembly',
            unique_together={('user', 'assembly')},
        ),
    ]
