# Generated by Django 3.0.4 on 2020-06-02 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_remove_project_document'),
        ('assemblies', '0009_auto_20200518_1027'),
        ('parts', '0008_auto_20200527_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('release_state', models.CharField(blank=True, max_length=50, null=True)),
                ('revision', models.CharField(blank=True, max_length=2, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assembly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assemblies.Assembly')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.Part')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project')),
            ],
        ),
    ]
