# Generated by Django 4.1.5 on 2023-02-10 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('documents', '0001_initial'), ('documents', '0002_document_document_number'), ('documents', '0003_document_document_controller'), ('documents', '0004_auto_20200607_2149'), ('documents', '0005_document_document_supplier'), ('documents', '0006_auto_20200702_2105'), ('documents', '0007_document_pdf'), ('documents', '0008_document_language'), ('documents', '0009_document_last_updated'), ('documents', '0010_auto_20200726_1637'), ('documents', '0011_document_zip_file'), ('documents', '0012_document_intenal'), ('documents', '0013_auto_20210901_1534'), ('documents', '0014_document_markdown'), ('documents', '0015_auto_20220122_1250'), ('documents', '0016_document_revision_locked'), ('documents', '0017_auto_20220609_1135'), ('documents', '0018_document_pcba_id'), ('documents', '0019_auto_20220609_1400'), ('documents', '0017_auto_20220501_1406'), ('documents', '0018_remove_document_pdf_complete'), ('documents', '0020_merge_20220617_1241'), ('documents', '0021_document_full_doc_number'), ('documents', '0022_auto_20220622_1341'), ('documents', '0023_auto_20220623_0800'), ('documents', '0024_auto_20220627_1601')]

    initial = True

    dependencies = [
        ('profiles', '0007_auto_20200602_2130'),
        ('assemblies', '0009_auto_20200518_1027'),
        ('parts', '0008_auto_20200527_2003'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_remove_project_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('release_state', models.CharField(blank=True, max_length=50, null=True)),
                ('revision', models.CharField(blank=True, max_length=2, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assembly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assemblies.assembly')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.part')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('document_number', models.CharField(blank=True, max_length=20, null=True)),
                ('quality_assurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile')),
                ('document_supplier', models.CharField(blank=True, max_length=50, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='documents')),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='zipFiles')),
                ('internal', models.BooleanField(null=True)),
                ('markdown', models.TextField(blank=True, max_length=100000, null=True)),
                ('pdf_raw', models.FileField(blank=True, null=True, upload_to='documents')),
                ('release_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('summary', models.TextField(blank=True, max_length=2000, null=True)),
                ('version_note', models.TextField(blank=True, max_length=1000, null=True)),
                ('revision_locked', models.BooleanField(default=False)),
                ('prefix_id', models.IntegerField(blank=True, default=-1)),
                ('pcba_id', models.IntegerField(blank=True, default=-1)),
                ('apply_ipr', models.BooleanField(blank=True, null=True)),
                ('front_page', models.BooleanField(blank=True, null=True)),
                ('revision_table', models.BooleanField(blank=True, null=True)),
                ('full_doc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('archived', models.CharField(blank=True, default='False', max_length=10)),
                ('archived_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document_Prefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField(blank=True, default=-1)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('prefix', models.CharField(blank=True, max_length=4, null=True)),
                ('part_doc', models.BooleanField(blank=True, null=True)),
                ('project_doc', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
