# Generated by Django 3.0.4 on 2020-06-02 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200602_2130'),
        ('documents', '0002_document_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Profile'),
        ),
    ]
