# Generated by Django 3.0.4 on 2020-06-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_document_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
