# Generated by Django 3.0.4 on 2020-06-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200607_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_supplier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
