# Generated by Django 3.0.4 on 2020-07-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_document_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_controller',
            new_name='quality_assurance',
        ),
    ]
