# Generated by Django 3.0.4 on 2020-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
