# Generated by Django 3.0.4 on 2020-11-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20200726_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='zipFiles'),
        ),
    ]
