# Generated by Django 3.0.4 on 2021-09-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_document_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='intenal',
            field=models.BooleanField(null=True),
        ),
    ]
