# Generated by Django 3.0.4 on 2021-10-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20210901_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='markdown',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
