# Generated by Django 3.0.4 on 2022-01-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_document_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_complete',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pdf_raw',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='document',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='version_note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
