# Generated by Django 3.0.4 on 2022-03-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20220122_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='revision_locked',
            field=models.BooleanField(default=False),
        ),
    ]
