# Generated by Django 3.0.4 on 2022-06-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_document_revision_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Prefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.IntegerField(blank=True, default=-1)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('prefix', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='prefix_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
