# Generated by Django 3.0.4 on 2022-05-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_document_revision_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='apply_ipr',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='front_page',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='revision_table',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
