# Generated by Django 3.0.4 on 2022-06-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_auto_20220501_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='pdf_complete',
        ),
    ]
