# Generated by Django 3.0.4 on 2022-06-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_document_pcba_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document_prefix',
            old_name='part_id',
            new_name='document_id',
        ),
    ]
