# Generated by Django 3.0.4 on 2022-06-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_auto_20220609_1400'),
        ('documents', '0018_remove_document_pdf_complete'),
    ]

    operations = [
    ]
