# Generated by Django 3.0.4 on 2022-06-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_document_full_doc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='full_doc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
