# Generated by Django 3.0.4 on 2022-06-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_auto_20220622_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archived',
            field=models.CharField(blank=True, default='False', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='archived_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
