# Generated by Django 3.0.4 on 2022-06-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_auto_20220623_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_prefix',
            name='part_doc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document_prefix',
            name='project_doc',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
