# Generated by Django 4.1.5 on 2023-02-10 11:17

import django.contrib.postgres.fields
from django.db import migrations, models
import tenants.storage_config


class Migration(migrations.Migration):

    replaces = [('documents', '0026_auto_20220704_1504'), ('documents', '0027_reference_list'), ('documents', '0028_document_prefix_archived_date'), ('documents', '0029_auto_20220728_1029'), ('documents', '0030_document_shared_document_link'), ('documents', '0031_auto_20221215_1021'), ('documents', '0031_auto_20221027_1910'), ('documents', '0032_merge_0031_auto_20221027_1910_0031_auto_20221215_1021'), ('documents', '0033_rename_revision_locked_document_is_latest_revision'), ('documents', '0034_rename_is_latest_revision_document_revision_locked'), ('documents', '0035_document_is_latest_revision'), ('documents', '0036_document_prefix_is_archived'), ('documents', '0037_document_is_archived')]

    dependencies = [
        ('documents', '0025_create_default_document_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_prefix',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Reference_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_doc_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('is_specification', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(blank=True, default=False), blank=True, default=list, null=True, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='document_prefix',
            name='archived_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document_prefix',
            name='archived',
            field=models.CharField(blank=True, default='False', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='shared_document_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=tenants.storage_config.GoogleCloudMediaStorage, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_raw',
            field=models.FileField(blank=True, null=True, storage=tenants.storage_config.GoogleCloudMediaStorage, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='document',
            name='previoius_revision_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.RenameField(
            model_name='document',
            old_name='revision_locked',
            new_name='revision_locked',
        ),
        migrations.AddField(
            model_name='document',
            name='is_latest_revision',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document_prefix',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
