# Generated by Django 3.0.4 on 2022-07-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_create_default_document_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_prefix',
            name='archive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document_prefix',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
