# Generated by Django 3.0.4 on 2022-07-17 11:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_auto_20220704_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_doc_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('is_specification', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(blank=True, default=False), blank=True, default=list, null=True, size=None)),
            ],
        ),
    ]
