# Generated by Django 3.0.4 on 2022-07-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_document_prefix_archived_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_prefix',
            name='archive',
        ),
        migrations.AddField(
            model_name='document_prefix',
            name='archived',
            field=models.CharField(blank=True, default='False', max_length=10),
        ),
    ]
