# Generated by Django 3.0.4 on 2022-08-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_auto_20220728_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared_document_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
