# Generated by Django 3.2.15 on 2022-12-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_auto_20221027_1910'),
        ('documents', '0031_auto_20221215_1021'),
    ]

    operations = [
    ]
