# Generated by Django 3.2.15 on 2023-01-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_merge_0031_auto_20221027_1910_0031_auto_20221215_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='revision_locked',
            new_name='is_latest_revision',
        ),
    ]
