# Generated by Django 3.2.15 on 2023-01-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_rename_revision_locked_document_is_latest_revision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='is_latest_revision',
            new_name='revision_locked',
        ),
    ]
