# Generated by Django 3.2.15 on 2023-01-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0034_rename_is_latest_revision_document_revision_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_latest_revision',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
