# Generated by Django 3.2.15 on 2023-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_document_prefix_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
