# Generated by Django 4.1.5 on 2023-03-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_auto_20220704_1504_squashed_0037_document_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='referenced_documents',
            field=models.ManyToManyField(blank=True, to='documents.document'),
        ),
    ]
