# Generated by Django 4.2 on 2023-04-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_alter_document_pdf_alter_document_pdf_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
