# Generated by Django 4.2 on 2023-04-28 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0040_alter_document_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='released_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
