# Generated by Django 4.2 on 2023-05-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0041_document_released_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='release_date',
            new_name='released_date',
        ),
    ]
