# Generated by Django 4.2 on 2024-02-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0043_document_errata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='archived',
        ),
    ]
