# Generated by Django 4.2 on 2024-03-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0044_remove_document_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='version_note',
            new_name='revision_notes',
        ),
    ]
