# Generated by Django 4.2.11 on 2024-09-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_task_tags'),
        ('documents', '0049_alter_document_referenced_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='document_tags', to='projects.tag'),
        ),
    ]
