# Generated by Django 4.2.11 on 2025-11-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0054_migrate_internal_to_protection_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='revision_count_major',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='revision_count_minor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='revision',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
