# Generated by Django 4.2.11 on 2025-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0058_populate_formatted_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='part_number',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
