# Generated by Django 4.2.11 on 2026-03-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_file_display_name'),
        ('documents', '0060_document_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='document_files', to='files.file'),
        ),
    ]
