# Generated by Django 4.2.11 on 2026-03-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0060_document_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_prefix',
            name='naming_convention',
            field=models.TextField(blank=True, help_text='Naming convention rules sent to AI for name suggestions', null=True),
        ),
    ]
