# Generated by Django 4.2.11 on 2026-03-22 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_file_display_name'),
        ('documents', '0062_document_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_print',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_pdf_print', to='files.file'),
        ),
        migrations.AddField(
            model_name='document',
            name='pdf_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_pdf_source', to='files.file'),
        ),
    ]
