# Generated by Django 4.2.11 on 2026-06-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0065_migrate_document_and_zip_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document_Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Optional page number in the referenced document.",
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Document referenced to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_references",
                        to="documents.document",
                    ),
                ),
            ],
        ),
    ]
