# Generated by Django 4.2.11 on 2026-06-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0066_document_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_reference',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
