# Generated by Django 3.0.4 on 2020-05-25 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_auto_20200412_0030'),
        ('assemblies', '0009_auto_20200518_1027'),
        ('parts', '0007_part_price_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('room', models.CharField(blank=True, max_length=150, null=True)),
                ('location_type', models.CharField(blank=True, max_length=150, null=True)),
                ('container_type', models.CharField(blank=True, max_length=150, null=True)),
                ('container_number', models.CharField(blank=True, max_length=150, null=True)),
                ('row_column', models.CharField(blank=True, max_length=150, null=True)),
                ('capacity_full', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assemblies.Assembly')),
                ('loaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Location')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.Part')),
            ],
        ),
    ]
