# Generated by Django 3.0.4 on 2020-05-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='loaction',
            new_name='location',
        ),
    ]
