# Generated by Django 3.0.4 on 2020-05-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200525_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='row_column',
            new_name='column',
        ),
        migrations.AddField(
            model_name='location',
            name='row',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
