# Generated by Django 3.0.4 on 2020-05-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200526_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='column',
            new_name='container_column',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='row',
            new_name='container_row',
        ),
        migrations.AddField(
            model_name='location',
            name='location_column',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_row',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
