# Generated by Django 3.0.4 on 2022-09-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_locationtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtypes',
            name='archived',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
