# Generated by Django 3.0.4 on 2022-09-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_locationtypes_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='archived',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
