# Generated by Django 3.0.4 on 2022-09-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_location_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
