# Generated by Django 3.0.4 on 2022-09-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_location_location_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='archived_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationtypes',
            name='archived_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
