# Generated by Django 3.2.15 on 2022-09-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20220905_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtypes',
            name='has_row_or_col',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
