# Generated by Django 3.2.15 on 2022-09-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_locationtypes_has_row_or_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='container_placement_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
