# Generated by Django 4.2 on 2023-05-07 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_squashed_0011_location_container_placement_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.locationtypes'),
        ),
    ]
