# Generated by Django 4.2 on 2023-05-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_location_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
