# Generated by Django 4.2.11 on 2024-08-28 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0051_pcba_external_part_number'),
        ('production', '0007_testdata_status'),
        ('inventory', '0014_location_location_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.lot'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pcba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbas.pcba'),
        ),
    ]
