# Generated by Django 4.2.11 on 2024-08-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_inventory_lot_inventory_pcba'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='current_total_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_latest',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
