# Generated by Django 3.0.4 on 2020-08-31 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assemblies', '0014_auto_20200726_1637'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(blank=True, max_length=2, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('test_document', models.FileField(blank=True, null=True, upload_to='test_documents')),
                ('firmware_version', models.CharField(blank=True, max_length=10, null=True)),
                ('assembly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assemblies.Assembly')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
