# Generated by Django 4.1.5 on 2023-02-10 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('serialnumbers', '0001_initial'), ('serialnumbers', '0002_serialnumber_last_updated'), ('serialnumbers', '0003_auto_20201213_1327'), ('serialnumbers', '0004_serialnumber_construction_finished'), ('serialnumbers', '0005_auto_20211203_1229'), ('serialnumbers', '0006_auto_20211210_1322')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assemblies', '0014_auto_20200726_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(blank=True, max_length=2, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('test_document', models.FileField(blank=True, null=True, upload_to='test_documents')),
                ('firmware_version', models.CharField(blank=True, max_length=10, null=True)),
                ('assembly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assemblies.assembly')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('construction_finished', models.BooleanField(blank=True, default=False, verbose_name=models.Case(models.When(state='Delivered', then=models.Value(True))))),
            ],
        ),
    ]
