# Generated by Django 3.0.4 on 2020-12-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialnumbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
