# Generated by Django 3.0.4 on 2020-12-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialnumbers', '0002_serialnumber_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialnumber',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
