# Generated by Django 3.0.4 on 2021-12-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialnumbers', '0003_auto_20201213_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='construction_finished',
            field=models.BooleanField(default=False),
        ),
    ]
