# Generated by Django 3.0.4 on 2021-12-03 11:29

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('serialnumbers', '0004_serialnumber_construction_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialnumber',
            name='construction_finished',
            field=models.BooleanField(verbose_name=django.db.models.expressions.Case(django.db.models.expressions.When(state='Delivered', then=django.db.models.expressions.Value(True)), default=False)),
        ),
    ]
