# Generated by Django 3.0.4 on 2021-12-10 12:22

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('serialnumbers', '0005_auto_20211203_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialnumber',
            name='construction_finished',
            field=models.BooleanField(blank=True, default=False, verbose_name=django.db.models.expressions.Case(django.db.models.expressions.When(state='Delivered', then=django.db.models.expressions.Value(True)))),
        ),
    ]
