# Generated by Django 4.2 on 2023-05-10 13:57

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    replaces = [('tenants', '0001_initial'), ('tenants', '0002_tenant_max_allowed_active_users'), ('tenants', '0003_signupinfo'), ('tenants', '0004_signupinfo_created_signupinfo_token_created'), ('tenants', '0005_rename_created_signupinfo_is_created')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('paid_until', models.DateField(blank=True, null=True)),
                ('on_trial', models.BooleanField(blank=True, default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('max_allowed_active_users', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=200)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('domain', models.CharField(blank=True, max_length=50)),
                ('userid_username', models.CharField(blank=True, max_length=500)),
                ('is_created', models.BooleanField(blank=True, default=False)),
                ('token_created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
