# Generated by Django 4.2 on 2023-05-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_signupinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupinfo',
            name='created',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='signupinfo',
            name='token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
