# Generated by Django 4.2 on 2023-05-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_signupinfo_created_signupinfo_token_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupinfo',
            old_name='created',
            new_name='is_created',
        ),
    ]
