# Generated by Django 3.0.4 on 2020-03-29 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200329_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
