# Generated by Django 3.0.4 on 2020-04-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200423_2133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
