# Generated by Django 4.1.5 on 2023-02-10 11:18

import django.contrib.postgres.fields
from django.db import migrations, models
import tenants.storage_config


class Migration(migrations.Migration):

    replaces = [('organizations', '0001_initial'), ('organizations', '0002_auto_20220620_0905'), ('organizations', '0003_organization_image_ids'), ('organizations', '0004_organization_logo_id'), ('organizations', '0005_organization_tenant_id'), ('organizations', '0006_alter_organization_tenant_id'), ('organizations', '0007_alter_organization_logo'), ('organizations', '0008_alter_organization_logo'), ('organizations', '0005_organization_test_user'), ('organizations', '0009_merge_20221227_1327'), ('organizations', '0010_remove_organization_system_license_and_more'), ('organizations', '0011_remove_organization_stripe_subscription_id_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_number', models.CharField(blank=True, default='-1', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('num_employees', models.IntegerField(blank=True, default=0)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, storage=tenants.storage_config.GoogleCloudMediaStorage, upload_to='images')),
                ('file_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), blank=True, null=True, size=None)),
                ('current_system_cost', models.IntegerField(blank=True, null=True)),
                ('image_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('logo_id', models.IntegerField(blank=True, null=True)),
                ('tenant_id', models.CharField(blank=True, max_length=50, null=True)),
                ('test_user', models.BooleanField(blank=True, default=False)),
                ('max_allowed_active_users', models.IntegerField(blank=True, default=1)),
                ('stripe_subscription_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, null=True, size=None)),
            ],
        ),
    ]
