# Generated by Django 3.0.4 on 2022-06-20 07:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_number', models.IntegerField(blank=True, default=-1, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('num_employees', models.IntegerField(blank=True, default=0)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('logo', models.ImageField(default=True, null=True, upload_to='')),
                ('file_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), blank=True, null=True, size=None)),
                ('system_license', models.CharField(blank=True, max_length=50, null=True)),
                ('system_license_contract', models.FileField(blank=True, null=True, upload_to='')),
                ('current_system_cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
