# Generated by Django 3.2.15 on 2022-09-23 08:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20220620_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='image_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
