# Generated by Django 3.2.15 on 2022-09-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_image_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
