# Generated by Django 3.2.15 on 2022-12-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_logo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='test_user',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
