# Generated by Django 3.2.15 on 2022-12-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_logo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tenant_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
