# Generated by Django 3.2.15 on 2022-12-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
