# Generated by Django 3.2.15 on 2022-12-15 10:45

from django.db import migrations, models
import tenants.storage_config


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=tenants.storage_config.GoogleCloudMediaStorage, upload_to='images'),
        ),
    ]
