# Generated by Django 3.2.15 on 2022-12-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_test_user'),
        ('organizations', '0008_alter_organization_logo'),
    ]

    operations = [
    ]
