# Generated by Django 4.1.5 on 2023-01-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_merge_20221227_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='system_license',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='system_license_contract',
        ),
        migrations.AddField(
            model_name='organization',
            name='max_allowed_active_users',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
