# Generated by Django 4.1.5 on 2023-01-23 12:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_remove_organization_system_license_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, null=True, size=None),
        ),
    ]
