# Generated by Django 4.1.5 on 2023-02-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_squashed_0011_remove_organization_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enforce_2fa',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
