# Generated by Django 4.1.5 on 2023-03-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_organization_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('currency_conversion_rates', models.JSONField(blank=True, default={})),
                ('currency_update_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='currency_conversion_rates',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='currency_update_time',
        ),
    ]
