# Generated by Django 4.2 on 2023-04-13 16:32

from django.db import migrations, models
import tenants.azure_storage


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_delete_currency_organization_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=tenants.azure_storage.CustomAzureStorage, upload_to='images'),
        ),
    ]
