# Generated by Django 4.2 on 2023-04-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_alter_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='current_storage_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='storage_limit',
            field=models.BigIntegerField(blank=True, default=5368709120),
        ),
    ]
