# Generated by Django 4.2 on 2023-04-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_organization_current_storage_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='current_storage_size',
            field=models.BigIntegerField(blank=True, default=1),
        ),
    ]
