# Generated by Django 4.2 on 2023-07-31 11:50

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_alter_organization_current_storage_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='component_vault_api_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=1024, null=True)),
        ),
    ]
