# Generated by Django 4.2 on 2023-09-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='checkout_status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
