# Generated by Django 4.2 on 2024-02-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_subscription_checkout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='assembly_is_enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='document_is_enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='pcba_is_enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='procurement_is_enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='time_tracking_is_enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
