# Generated by Django 4.2 on 2024-04-18 07:47

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0023_organizationapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationapikey',
            name='encrypted_api_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=2048, null=True)),
        ),
    ]
