# Generated by Django 4.2.11 on 2024-06-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0024_organizationapikey_encrypted_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_allowed_active_viewer_users',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
