# Generated by Django 4.2.11 on 2025-10-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0027_organization_billing_address_organization_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='revision_format',
            field=models.CharField(blank=True, choices=[('major-only', 'Major Only (1, 2, 3...)'), ('major-minor', 'Major-Minor (1-0, 1-1, 2-0...)')], default='major-minor', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='use_number_revisions',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
