# Generated by Django 4.2.11 on 2025-10-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0028_organization_revision_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='revision_separator',
            field=models.CharField(blank=True, choices=[('-', 'Dash (1-0, 1-1, 2-0...)'), ('.', 'Dot (1.0, 1.1, 2.0...)')], default='-', max_length=5),
        ),
    ]
