# Generated by Django 4.2.11 on 2025-11-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0029_add_revision_separator'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='production_is_enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
