# Generated by Django 4.2.11 on 2025-11-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0030_organization_production_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='revision_format',
            field=models.CharField(blank=True, choices=[('major-only', 'Major Only'), ('major-minor', 'Major-Minor')], default='major-minor', help_text='Format for revisions. Applies to both letter (A, B vs A-0, A-1) and number (1, 2 vs 1-0, 1-1) systems.', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='revision_separator',
            field=models.CharField(blank=True, choices=[('-', 'Dash'), ('.', 'Dot')], default='-', help_text='Separator between major and minor revisions (e.g., A-0 or A.0, 1-0 or 1.0)', max_length=5),
        ),
    ]
