# Generated by Django 4.2.11 on 2025-11-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0031_alter_organization_revision_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='full_part_number_template',
            field=models.CharField(blank=True, default='<prefix><part_number><revision>', help_text='Template for formatting full part numbers. Use <prefix>, <part_number>, <major_revision>, <minor_revision>', max_length=100),
        ),
    ]
