# Generated by Django 4.2.11 on 2025-11-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0032_organization_full_part_number_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='formatted_revision_template',
            field=models.CharField(blank=True, default='<major_revision>', max_length=100),
        ),
    ]
