# Generated by Django 4.2.11 on 2025-11-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0033_organization_formatted_revision_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='customer_is_enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
