# Generated by Django 4.2.11 on 2025-11-20 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_alter_project_project_number'),
        ('organizations', '0034_organization_customer_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_released_bom_items_assembly', models.BooleanField(blank=True, default=False, help_text='Require all BOM items to be released before releasing an Assembly')),
                ('require_released_bom_items_pcba', models.BooleanField(blank=True, default=False, help_text='Require all BOM items to be released before releasing a PCBA')),
                ('override_permission', models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Project Owner', 'Project Owner'), ('User', 'User')], default='Admin', help_text='Minimum role required to override release rules', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='organizations.organization')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='projects.project')),
            ],
            options={
                'verbose_name': 'Release Rules',
                'verbose_name_plural': 'Release Rules',
            },
        ),
        migrations.AddConstraint(
            model_name='rules',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('organization__isnull', False), ('project__isnull', True)), models.Q(('organization__isnull', True), ('project__isnull', False)), _connector='OR'), name='release_rules_org_or_project'),
        ),
    ]
