# Generated by Django 4.2.11 on 2025-11-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0035_rules_rules_release_rules_org_or_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='require_review_on_assembly',
            field=models.BooleanField(blank=True, default=False, help_text='Require review approval before releasing an Assembly'),
        ),
        migrations.AddField(
            model_name='rules',
            name='require_review_on_document',
            field=models.BooleanField(blank=True, default=False, help_text='Require review approval before releasing a Document'),
        ),
        migrations.AddField(
            model_name='rules',
            name='require_review_on_part',
            field=models.BooleanField(blank=True, default=False, help_text='Require review approval before releasing a Part'),
        ),
        migrations.AddField(
            model_name='rules',
            name='require_review_on_pcba',
            field=models.BooleanField(blank=True, default=False, help_text='Require review approval before releasing a PCBA'),
        ),
    ]
