# Generated by Django 4.2.11 on 2025-11-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0036_rules_require_review_on_assembly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digikey_client_id', models.CharField(blank=True, max_length=500, null=True)),
                ('digikey_client_secret', models.CharField(blank=True, max_length=500, null=True)),
                ('digikey_field_mapping', models.JSONField(blank=True, default=dict, help_text='Maps DigiKey API response fields to part model fields')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Integration Settings',
                'verbose_name_plural': 'Integration Settings',
            },
        ),
    ]
