# Generated by Django 4.2.11 on 2025-11-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0037_add_integration_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='digikey_locale_currency',
            field=models.CharField(blank=True, default='USD', help_text='DigiKey locale currency code (e.g., USD, EUR, GBP). Default: USD', max_length=10),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='digikey_locale_language',
            field=models.CharField(blank=True, default='en', help_text='DigiKey locale language code (e.g., en, de, fr). Default: en', max_length=10),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='digikey_locale_site',
            field=models.CharField(blank=True, default='US', help_text='DigiKey locale site code (e.g., US, CA, UK, DE). Default: US', max_length=10),
        ),
    ]
