# Generated by Django 4.2.11 on 2025-11-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0022_poitem_quantity_received'),
        ('organizations', '0038_integrationsettings_digikey_locale_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='digikey_supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier to use when creating prices from DigiKey parts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digikey_integration_settings', to='purchasing.supplier'),
        ),
    ]
