# Generated by Django 4.2.11 on 2025-11-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0039_integrationsettings_digikey_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='start_major_revision_at_one',
            field=models.BooleanField(blank=True, default=False, help_text='When enabled and using number-based revisions, display major revisions starting at 1 instead of 0 (e.g., 1, 2, 3... instead of 0, 1, 2...). Minor revisions always start at 0. Does not affect how revisions are stored in the database.'),
        ),
    ]
