# Generated by Django 4.2.11 on 2025-11-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0040_add_start_major_revision_at_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='nexar_client_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='nexar_client_secret',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='revision_format',
            field=models.CharField(blank=True, choices=[('major-only', 'Major Only'), ('major-minor', 'Major-Minor')], default='major-minor', help_text='Format for revisions. Applies to both letter (A, B vs A-0, A-1) and number systems. For number systems, the starting value (0 or 1) is controlled by start_major_revision_at_one setting.', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='start_major_revision_at_one',
            field=models.BooleanField(blank=True, default=False, help_text='When enabled and using number-based revisions, display major revisions starting at 1 instead of 0 (e.g., 1, 2, 3... instead of 0, 1, 2...). Minor revisions always start at 0 regardless of this setting (e.g., 1-0, 1-1, 1-2, 2-0...). Does not affect how revisions are stored in the database.'),
        ),
    ]
