# Generated by Django 4.2.11 on 2025-11-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0041_integrationsettings_nexar_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='full_document_number_template',
            field=models.CharField(blank=True, default='<prefix><project_number>-<document_number><revision>', help_text='Template for formatting full document numbers. Use <prefix>, <project_number>, <part_number>, <document_number>, <major_revision>, <minor_revision>, <revision>, <day>, <month>, <year>', max_length=100),
        ),
    ]
