# Generated by Django 4.2.11 on 2025-11-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0042_organization_full_document_number_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='document_revision_format',
            field=models.CharField(blank=True, choices=[('major-only', 'Major Only'), ('major-minor', 'Major-Minor')], default='major-minor', help_text='Format for document revisions. Major-only uses single revisions (A, B, C or 0, 1, 2), while major-minor allows sub-revisions (A-0, A-1 or 0-0, 0-1)', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='document_start_major_revision_at_one',
            field=models.BooleanField(blank=True, default=False, help_text='When enabled and using number-based revisions for documents, display major revisions starting at 1 instead of 0 (e.g., 1, 2, 3... instead of 0, 1, 2...). Minor revisions always start at 0 regardless of this setting.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='document_use_number_revisions',
            field=models.BooleanField(blank=True, default=False, help_text='When enabled, documents will use number-based revisions instead of letters (0, 1, 2... instead of A, B, C...)'),
        ),
    ]
