# Generated by Django 4.2.11 on 2025-11-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0043_organization_document_revision_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='supplier_is_enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
