# Generated by Django 4.2.11 on 2025-11-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0044_organization_supplier_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='inventory_is_enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
