# Generated by Django 4.2.11 on 2025-11-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0045_organization_inventory_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='eco_is_enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
