# Generated by Django 4.2.11 on 2025-11-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0046_organization_eco_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='require_all_affected_items_reviewed_for_eco',
            field=models.BooleanField(blank=True, default=False, help_text='Require all affected items to be reviewed before releasing an ECO'),
        ),
        migrations.AddField(
            model_name='rules',
            name='require_review_on_eco',
            field=models.BooleanField(blank=True, default=False, help_text='Require review approval before releasing an ECO'),
        ),
    ]
