# Generated by Django 4.2.11 on 2025-11-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0047_rules_require_all_affected_items_reviewed_for_eco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='require_bom_items_released_or_in_eco',
            field=models.BooleanField(blank=True, default=False, help_text='Require BOM items of affected assemblies/PCBAs to be released or included in the ECO'),
        ),
    ]
