# Generated by Django 4.2.11 on 2025-11-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0048_rules_require_bom_items_released_or_in_eco'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='require_matched_bom_items_assembly',
            field=models.BooleanField(blank=True, default=False, help_text='Require all BOM items to be matched to a Part, PCBA, or Assembly before releasing an Assembly'),
        ),
        migrations.AddField(
            model_name='rules',
            name='require_matched_bom_items_pcba',
            field=models.BooleanField(blank=True, default=False, help_text='Require all BOM items to be matched to a Part, PCBA, or Assembly before releasing a PCBA'),
        ),
    ]
