# Generated by Django 4.2.11 on 2025-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0049_rules_require_matched_bom_items_assembly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='require_bom_items_matched_for_eco_assembly',
            field=models.BooleanField(blank=True, default=False, help_text='Require all BOM items of affected Assemblies to be matched to a Part, PCBA, or Assembly before releasing an ECO'),
        ),
        migrations.AddField(
            model_name='rules',
            name='require_bom_items_matched_for_eco_pcba',
            field=models.BooleanField(blank=True, default=False, help_text='Require all BOM items of affected PCBAs to be matched to a Part, PCBA, or Assembly before releasing an ECO'),
        ),
    ]
