# Generated by Django 4.2.11 on 2025-11-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0050_rules_require_bom_items_matched_for_eco_assembly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='require_revision_notes_on_affected_items',
            field=models.BooleanField(blank=True, default=False, help_text='Require all affected items in an ECO to have revision notes before releasing'),
        ),
    ]
