# Generated by Django 4.2.11 on 2026-01-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0053_add_odoo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='odoo_default_product_type',
            field=models.CharField(blank=True, choices=[('goods', 'Goods'), ('service', 'Service')], default='goods', help_text='Default product type in Odoo', max_length=50),
        ),
    ]
