# Generated by Django 4.2.11 on 2026-01-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0054_alter_integrationsettings_odoo_default_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='odoo_default_product_type',
            field=models.CharField(blank=True, choices=[('consu', 'Goods'), ('service', 'Service'), ('combo', 'Combo')], default='consu', help_text='Default product type in Odoo', max_length=50),
        ),
    ]
