# Generated by Django 4.2.11 on 2026-01-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0055_alter_integrationsettings_odoo_default_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='odoo_category_assemblies',
            field=models.CharField(blank=True, default='Manufactured', help_text='Product category name for Assemblies', max_length=200),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='odoo_category_parts_pcbas',
            field=models.CharField(blank=True, default='Purchased Goods', help_text='Product category name for Parts and PCBAs', max_length=200),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='odoo_default_is_storable',
            field=models.BooleanField(default=True, help_text="Default 'Track Inventory' setting for new products"),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='odoo_default_purchase_ok',
            field=models.BooleanField(default=True, help_text="Default 'Can be Purchased' setting for new products"),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='odoo_default_rent_ok',
            field=models.BooleanField(default=False, help_text="Default 'Can be Rented' setting for new products"),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='odoo_default_sale_ok',
            field=models.BooleanField(default=False, help_text="Default 'Can be Sold' setting for new products"),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='odoo_default_tracking',
            field=models.CharField(blank=True, choices=[('none', 'By Quantity'), ('lot', 'By Lots'), ('serial', 'By Serial Numbers')], default='none', help_text='Default inventory tracking method for new products', max_length=20),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='odoo_update_fields_existing',
            field=models.JSONField(blank=True, default=list, help_text='List of fields to update when product already exists in Odoo. Options: name, description, image'),
        ),
    ]
