# Generated by Django 4.2.11 on 2026-01-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0056_integrationsettings_odoo_category_assemblies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationsettings',
            name='odoo_category_parts_pcbas',
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='odoo_category_parts',
            field=models.CharField(blank=True, default='Purchased Goods', help_text='Product category name for Parts', max_length=200),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='odoo_category_pcbas',
            field=models.CharField(blank=True, default='Purchased Goods', help_text='Product category name for PCBAs', max_length=200),
        ),
    ]
