# Generated by Django 4.2.11 on 2026-03-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0057_remove_integrationsettings_odoo_category_parts_pcbas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='currency_api_key',
            field=models.CharField(blank=True, help_text='API key for ExchangeRate-API (v6.exchangerate-api.com)', max_length=500, null=True),
        ),
    ]
