# Generated by Django 4.2.11 on 2026-03-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0059_rules_require_image_on_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='ai_api_key',
            field=models.CharField(blank=True, help_text='Anthropic API key for AI-powered features', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='ai_model',
            field=models.CharField(blank=True, default='claude-sonnet-4-20250514', help_text='AI model identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='ai_provider',
            field=models.CharField(blank=True, default='anthropic', help_text='AI provider name', max_length=50),
        ),
    ]
