# Generated by Django 4.2.11 on 2026-03-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0060_integrationsettings_ai_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='require_pdf_on_document',
            field=models.BooleanField(blank=True, default=False, help_text='Require a PDF to be uploaded before releasing a Document'),
        ),
    ]
