# Generated by Django 4.2.11 on 2026-05-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0061_rules_require_pdf_on_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='odoo_auto_push_assemblies_on_release',
            field=models.BooleanField(default=True, help_text='When auto-push on release is enabled, include assemblies (parts and PCBAs still push when this is off)'),
        ),
    ]
