# Generated by Django 4.2.11 on 2026-06-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0062_odoo_auto_push_assemblies_on_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='email_host',
            field=models.CharField(blank=True, help_text='SMTP server hostname (e.g. smtp.gmail.com)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='SMTP login password or app-specific password', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='SMTP login username / email address', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='email_port',
            field=models.IntegerField(blank=True, help_text='SMTP server port (e.g. 587 for TLS, 465 for SSL)', null=True),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='email_sender',
            field=models.CharField(blank=True, help_text='From-address used when sending emails (e.g. noreply@yourcompany.com)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='Use implicit SSL/TLS when connecting to the SMTP server (mutually exclusive with TLS)'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use STARTTLS when connecting to the SMTP server'),
        ),
    ]
