# Generated by Django 4.2.11 on 2025-11-29 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0024_tableview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release_state', models.CharField(blank=True, max_length=50)),
                ('released_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_created_by', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_released_by', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_responsible', to='profiles.profile')),
            ],
        ),
    ]
