# Generated by Django 4.2.11 on 2025-11-29 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0060_document_thumbnail'),
        ('eco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eco',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.markdowntext'),
        ),
        migrations.AddField(
            model_name='eco',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
