# Generated by Django 4.2.11 on 2025-11-29 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_tableview'),
        ('eco', '0002_eco_description_eco_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eco',
            name='quality_assurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_quality_assurance', to='profiles.profile'),
        ),
    ]
