# Generated by Django 4.2.11 on 2025-11-29 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0056_populate_formatted_revision'),
        ('parts', '0093_alter_part_datasheet'),
        ('documents', '0060_document_thumbnail'),
        ('pcbas', '0060_populate_formatted_revision'),
        ('eco', '0003_eco_quality_assurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_affected_items', to='assemblies.assembly')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_affected_items', to='documents.document')),
                ('eco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_items', to='eco.eco')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_affected_items', to='parts.part')),
                ('pcba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_affected_items', to='pcbas.pcba')),
            ],
        ),
    ]
