# Generated by Django 4.2.11 on 2025-11-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0004_affecteditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='eco',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
