# Generated by Django 4.2.11 on 2025-11-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_alter_project_project_number'),
        ('eco', '0005_eco_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='eco',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecos', to='projects.project'),
        ),
        migrations.AddField(
            model_name='eco',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='eco_tags', to='projects.tag'),
        ),
    ]
