# Generated by Django 4.2.11 on 2026-03-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_issues_assignee'),
        ('eco', '0006_eco_project_eco_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='affecteditem',
            name='issues',
            field=models.ManyToManyField(blank=True, related_name='eco_affected_items', to='projects.issues'),
        ),
    ]
