# Generated by Django 4.1.5 on 2023-02-10 11:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('reimbursements', '0001_initial'), ('reimbursements', '0002_auto_20201116_2051'), ('reimbursements', '0003_reimbursement_state')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, null=True, size=None)),
                ('price', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10), default=list, null=True, size=None)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='reimbursement_pdfs')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='reimbursement_attachements')),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
