# Generated by Django 3.0.4 on 2020-11-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='reimbursement_pdfs'),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='reimbursement_attachements'),
        ),
    ]
