# Generated by Django 3.0.4 on 2020-11-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0002_auto_20201116_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
