# Generated by Django 4.1.5 on 2023-02-10 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('profiles', '0001_initial'), ('profiles', '0002_auto_20200423_2239'), ('profiles', '0003_auto_20200423_2248'), ('profiles', '0004_auto_20200424_2008'), ('profiles', '0005_auto_20200426_1840'), ('profiles', '0006_auto_20200504_2256'), ('profiles', '0007_auto_20200602_2130'), ('profiles', '0008_profile_is_active'), ('profiles', '0009_profile_role'), ('profiles', '0010_profile_organization_id'), ('profiles', '0011_remove_profile_is_active'), ('profiles', '0012_profile_is_active'), ('profiles', '0013_auto_20230105_1201')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('personal_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('position_percentage', models.CharField(blank=True, max_length=3, null=True)),
                ('contract', models.FileField(blank=True, null=True, upload_to='')),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, default='User', max_length=50)),
                ('organization_id', models.IntegerField(blank=True, default=-1)),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
