# Generated by Django 4.1.5 on 2023-02-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_squashed_0013_auto_20230105_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_hash',
            field=models.CharField(blank=True, max_length=513, null=True),
        ),
    ]
