# Generated by Django 4.1.5 on 2023-02-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_mfa_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_validated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
