# Generated by Django 4.2 on 2023-12-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profile_mfa_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=800, null=True)),
                ('uri', models.CharField(blank=True, max_length=2097152, null=True)),
                ('app', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
