# Generated by Django 4.2 on 2024-04-23 18:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_apps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
