# Generated by Django 4.2 on 2024-04-23 19:07

from django.db import migrations

def set_default_allowed_apps(apps, schema_editor):
    Profile = apps.get_model('profiles', 'Profile')  # Replace 'your_app_name' with your actual app name
    profiles = Profile.objects.all()
    default_apps = ['timesheet', 'customers', 'projects', 'requirements', 'documents', 'parts', 'assemblies', 'pcbas', 'production', 'procurement']
    for profile in profiles:
        profile.allowed_apps = default_apps
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_profile_allowed_apps'),
    ]

    operations = [
          migrations.RunPython(set_default_allowed_apps),
    ]
