# Generated by Django 4.2.11 on 2024-09-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_profile_notify_user_on_added_to_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_project_notification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
