# Generated by Django 4.2.11 on 2025-11-08 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0023_notification_is_project_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(help_text="Name of the table (e.g., 'parts', 'assemblies', 'pcbas')", max_length=100)),
                ('name', models.CharField(help_text='User-friendly name for this view', max_length=200)),
                ('is_shared', models.BooleanField(default=False, help_text='If True, view is available to all users')),
                ('columns', models.JSONField(default=list, help_text='List of column keys to display')),
                ('filters', models.JSONField(default=dict, help_text='Active filters as key-value pairs')),
                ('sorted_column', models.CharField(blank=True, help_text='Key of the sorted column', max_length=100, null=True)),
                ('sort_order', models.CharField(default='asc', help_text="Sort order: 'asc' or 'desc'", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['table_name', 'user'], name='profiles_ta_table_n_d1373d_idx'), models.Index(fields=['table_name', 'is_shared'], name='profiles_ta_table_n_1c3ff2_idx')],
                'unique_together': {('table_name', 'name', 'user')},
            },
        ),
    ]
