# Generated by Django 3.0.4 on 2020-11-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesopportunity',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
