# Generated by Django 3.0.4 on 2020-11-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_opportunities', '0002_salesopportunity_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesopportunity',
            old_name='created_by',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='salesopportunity',
            old_name='comment_profile',
            new_name='comment_user',
        ),
    ]
