# Generated by Django 3.0.4 on 2021-03-01 13:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_opportunities', '0003_auto_20201115_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesopportunity',
            name='comment_content',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=5000), default=list, null=True, size=None),
        ),
    ]
