# Generated by Django 3.0.4 on 2021-04-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_opportunities', '0004_auto_20210301_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesopportunity',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
