# Generated by Django 3.0.4 on 2021-05-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_opportunities', '0005_auto_20210430_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesopportunity',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
