# Generated by Django 4.1.5 on 2023-02-10 11:17

from django.db import migrations, models
import tenants.storage_config


class Migration(migrations.Migration):

    replaces = [('files', '0001_initial'), ('files', '0002_file_active'), ('files', '0003_auto_20220916_0817'), ('files', '0004_image'), ('files', '0005_auto_20221215_1021'), ('files', '0006_file_last_updated'), ('files', '0007_image_last_updated')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=tenants.storage_config.GoogleCloudMediaStorage, upload_to='documents/')),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.IntegerField(blank=True, default=1)),
                ('archived', models.IntegerField(blank=True, default=0)),
                ('archived_date', models.DateField(blank=True, null=True)),
                ('download_count', models.IntegerField(blank=True, default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=tenants.storage_config.GoogleCloudMediaStorage, upload_to='images/')),
                ('image_name', models.CharField(blank=True, max_length=50, null=True)),
                ('download_count', models.IntegerField(blank=True, default=0)),
                ('archived', models.IntegerField(blank=True, default=0)),
                ('archived_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
