# Generated by Django 3.0.4 on 2022-06-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='active',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
