# Generated by Django 3.2.15 on 2022-09-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='archived',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='archived_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='download_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
