# Generated by Django 3.2.15 on 2022-09-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20220916_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='images/')),
                ('image_name', models.CharField(blank=True, max_length=50, null=True)),
                ('download_count', models.IntegerField(blank=True, default=0)),
                ('archived', models.IntegerField(blank=True, default=0)),
                ('archived_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
