# Generated by Django 3.2.15 on 2022-12-15 10:21

from django.db import migrations, models
import tenants.storage_config


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, storage=tenants.storage_config.GoogleCloudMediaStorage, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(blank=True, null=True, storage=tenants.storage_config.GoogleCloudMediaStorage, upload_to='images/'),
        ),
    ]
