# Generated by Django 3.2.15 on 2023-01-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20221215_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
