# Generated by Django 3.2.15 on 2023-01-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
