# Generated by Django 4.2 on 2023-04-13 16:32

from django.db import migrations, models
import tenants.azure_storage


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_squashed_0007_image_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, storage=tenants.azure_storage.CustomAzureStorage, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(blank=True, null=True, storage=tenants.azure_storage.CustomAzureStorage, upload_to='images/'),
        ),
    ]
