# Generated by Django 4.2 on 2024-06-11 16:36

from django.db import migrations, models
import tenants.azure_storage


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_image_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_compressed',
            field=models.FileField(
                blank=True, null=True, storage=tenants.azure_storage.CustomAzureStorage, upload_to='images/compressed/'),
        ),
    ]
