# Generated by Django 4.2.11 on 2024-07-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_alter_file_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='display_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
