# Generated by Django 4.2.11 on 2026-04-04 17:26

from django.db import migrations, models
import tenants.azure_storage


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_filelock'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='step_glb_conversion',
            field=models.FileField(blank=True, null=True, storage=tenants.azure_storage.CustomAzureStorage, upload_to='converted/'),
        ),
    ]
