# Generated by Django 4.2.11 on 2026-04-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_file_step_glb_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_category',
            field=models.CharField(blank=True, choices=[('design', 'Design'), ('production', 'Production'), ('other', 'Other')], default='design', help_text='Category of the file: Design, Production, or Other', max_length=20),
        ),
    ]
