# Generated by Django 4.2.11 on 2026-04-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_file_file_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the file was first uploaded', null=True),
        ),
    ]
