# Generated by Django 3.0.4 on 2020-06-23 15:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0008_auto_20200527_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pcba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField()),
                ('top_level_assembly', models.CharField(blank=True, max_length=5)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('release_state', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mpn', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), default=list, null=True, size=None)),
                ('refdes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), default=list, null=True, size=None)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='gerber_files')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pcb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.Part')),
            ],
        ),
    ]
