# Generated by Django 4.1.5 on 2023-02-10 11:19

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('pcbas', '0001_initial'), ('pcbas', '0002_auto_20200624_0906'), ('pcbas', '0003_auto_20200624_1633'), ('pcbas', '0005_pcba_revision'), ('pcbas', '0006_remove_pcba_revision'), ('pcbas', '0007_pcba_revision'), ('pcbas', '0008_pcba_last_updated'), ('pcbas', '0009_auto_20200726_1637'), ('pcbas', '0010_pcba_revision_notes'), ('pcbas', '0011_auto_20200813_0934'), ('pcbas', '0012_pcba_nobom'), ('pcbas', '0013_auto_20200927_1147'), ('pcbas', '0014_auto_20210220_1629'), ('pcbas', '0015_pcba_comments_for_next_revision'), ('pcbas', '0016_auto_20210401_1823'), ('pcbas', '0017_auto_20220107_1419'), ('pcbas', '0018_auto_20220107_1455'), ('pcbas', '0019_auto_20220107_1544'), ('pcbas', '0020_auto_20220107_1814'), ('pcbas', '0017_auto_20211210_1444'), ('pcbas', '0018_auto_20211210_1606'), ('pcbas', '0021_merge_20220217_1223'), ('pcbas', '0022_pcba_bom'), ('pcbas', '0023_pcba_bom_saved'), ('pcbas', '0024_pcba_pcba_bom_id'), ('pcbas', '0025_pcba_reference_list_id'), ('pcbas', '0026_pcba_pcb_renders'), ('pcbas', '0027_pcba_full_part_number'), ('pcbas', '0028_auto_20220922_1013'), ('pcbas', '0029_pcba_project'), ('pcbas', '0030_pcba_is_latest_revision'), ('pcbas', '0031_pcba_is_archived')]

    initial = True

    dependencies = [
        ('parts', '0008_auto_20200527_2003'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0020_project_archived_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pcba_bom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcba_id', models.IntegerField(blank=True, null=True)),
                ('part_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Pcba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('release_state', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mpn', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), blank=True, default=list, null=True, size=None)),
                ('refdes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), blank=True, default=list, null=True, size=None)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='gerber_files')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pcb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.part')),
                ('dnm', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), blank=True, default=list, null=True, size=None)),
                ('revision', models.CharField(blank=True, max_length=3, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('revision_notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('assembly_pdf', models.FileField(blank=True, null=True, upload_to='assembly_pdf')),
                ('layout_image', models.FileField(blank=True, null=True, upload_to='layout_image')),
                ('manufacture_pdf', models.FileField(blank=True, null=True, upload_to='manufacture_pdf')),
                ('schematic_pdf', models.FileField(blank=True, null=True, upload_to='schematic_pdf')),
                ('schematic_pdf_monochrome', models.FileField(blank=True, null=True, upload_to='schematic_pdf_monochrome')),
                ('nobom', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), blank=True, default=list, null=True, size=None)),
                ('comments_for_next_revision', models.TextField(blank=True, max_length=10000, null=True)),
                ('extra_file1', models.FileField(blank=True, null=True, upload_to='extra_file1')),
                ('extra_file2', models.FileField(blank=True, null=True, upload_to='extra_file2')),
                ('extra_file3', models.FileField(blank=True, null=True, upload_to='extra_file3')),
                ('next_pcba', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), blank=True, null=True, size=None)),
                ('prev_pcba', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), blank=True, null=True, size=None)),
                ('bom_saved', models.BooleanField(blank=True, default=False)),
                ('pcba_bom_id', models.IntegerField(blank=True, null=True)),
                ('reference_list_id', models.IntegerField(blank=True, default=-1)),
                ('pcb_renders', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('full_part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('archived', models.IntegerField(blank=True, default=0)),
                ('archived_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('is_latest_revision', models.BooleanField(blank=True, default=False)),
                ('is_archived', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
