# Generated by Django 3.0.4 on 2020-06-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcba',
            name='top_level_assembly',
        ),
        migrations.AlterField(
            model_name='pcba',
            name='part_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
