# Generated by Django 3.0.4 on 2020-06-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0003_auto_20200624_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='revision',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
