# Generated by Django 3.0.4 on 2020-06-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0005_pcba_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcba',
            name='revision',
        ),
    ]
