# Generated by Django 3.0.4 on 2020-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0007_pcba_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
