# Generated by Django 3.0.4 on 2020-08-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0009_auto_20200726_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='revision_notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
