# Generated by Django 3.0.4 on 2020-08-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0010_pcba_revision_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='assembly_pdf',
            field=models.FileField(blank=True, null=True, upload_to='assembly_pdf'),
        ),
        migrations.AddField(
            model_name='pcba',
            name='layout_image',
            field=models.FileField(blank=True, null=True, upload_to='layout_image'),
        ),
        migrations.AddField(
            model_name='pcba',
            name='manufacture_pdf',
            field=models.FileField(blank=True, null=True, upload_to='manufacture_pdf'),
        ),
        migrations.AddField(
            model_name='pcba',
            name='schematic_pdf',
            field=models.FileField(blank=True, null=True, upload_to='schematic_pdf'),
        ),
        migrations.AddField(
            model_name='pcba',
            name='schematic_pdf_monochrome',
            field=models.FileField(blank=True, null=True, upload_to='schematic_pdf_monochrome'),
        ),
    ]
