# Generated by Django 3.0.4 on 2020-08-13 13:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0011_auto_20200813_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='nobom',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), default=list, null=True, size=None),
        ),
    ]
