# Generated by Django 3.0.4 on 2021-02-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0013_auto_20200927_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcba',
            name='revision_notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
