# Generated by Django 3.0.4 on 2021-04-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0014_auto_20210220_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='comments_for_next_revision',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
