# Generated by Django 3.0.4 on 2021-04-01 16:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0015_pcba_comments_for_next_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcba',
            name='dnm',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pcba',
            name='mpn',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pcba',
            name='nobom',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pcba',
            name='refdes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), blank=True, default=list, null=True, size=None),
        ),
    ]
