# Generated by Django 3.0.4 on 2021-12-10 13:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0016_auto_20210401_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='next_pcba',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='pcba',
            name='prev_pcba',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None),
        ),
    ]
