# Generated by Django 3.0.4 on 2022-01-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0016_auto_20210401_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='extra_file_pcba1',
            field=models.FileField(blank=True, null=True, upload_to='extra_file_pcba1'),
        ),
        migrations.AddField(
            model_name='pcba',
            name='extra_file_pcba2',
            field=models.FileField(blank=True, null=True, upload_to='extra_file_pcba2'),
        ),
        migrations.AddField(
            model_name='pcba',
            name='extra_file_pcba3',
            field=models.FileField(blank=True, null=True, upload_to='extra_file_pcba3'),
        ),
    ]
