# Generated by Django 3.0.4 on 2021-12-10 15:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0017_auto_20211210_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcba',
            name='next_pcba',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pcba',
            name='prev_pcba',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), blank=True, null=True, size=None),
        ),
    ]
