# Generated by Django 3.0.4 on 2022-01-07 13:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0017_auto_20220107_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcba',
            name='extra_file_pcba1',
        ),
        migrations.RemoveField(
            model_name='pcba',
            name='extra_file_pcba2',
        ),
        migrations.RemoveField(
            model_name='pcba',
            name='extra_file_pcba3',
        ),
        migrations.AddField(
            model_name='pcba',
            name='extra_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, null=True, upload_to='extra_files'), blank=True, null=True, size=None),
        ),
    ]
