# Generated by Django 3.0.4 on 2022-01-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0018_auto_20220107_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcba',
            name='extra_files',
        ),
        migrations.AddField(
            model_name='pcba',
            name='extra_file1',
            field=models.FileField(blank=True, null=True, upload_to='extra_file1'),
        ),
        migrations.AddField(
            model_name='pcba',
            name='extra_file2',
            field=models.FileField(blank=True, null=True, upload_to='extra_file1'),
        ),
        migrations.AddField(
            model_name='pcba',
            name='extra_file3',
            field=models.FileField(blank=True, null=True, upload_to='extra_file1'),
        ),
    ]
