# Generated by Django 3.0.4 on 2022-01-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0019_auto_20220107_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcba',
            name='extra_file2',
            field=models.FileField(blank=True, null=True, upload_to='extra_file2'),
        ),
        migrations.AlterField(
            model_name='pcba',
            name='extra_file3',
            field=models.FileField(blank=True, null=True, upload_to='extra_file3'),
        ),
    ]
