# Generated by Django 3.0.4 on 2022-02-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0020_auto_20220107_1814'),
        ('pcbas', '0018_auto_20211210_1606'),
    ]

    operations = [
    ]
