# Generated by Django 3.0.4 on 2022-03-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0022_pcba_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='bom_saved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
