# Generated by Django 3.0.4 on 2022-03-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0023_pcba_bom_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='pcba_bom_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
