# Generated by Django 3.0.4 on 2022-07-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0024_pcba_pcba_bom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='reference_list_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
