# Generated by Django 3.0.4 on 2022-08-07 08:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0025_pcba_reference_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='pcb_renders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
