# Generated by Django 3.0.4 on 2022-08-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0026_pcba_pcb_renders'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='full_part_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
