# Generated by Django 3.2.15 on 2022-09-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0027_pcba_full_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='archived',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pcba',
            name='archived_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
