# Generated by Django 4.1.5 on 2023-02-17 19:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0001_squashed_0031_pcba_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='bom_part_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
