# Generated by Django 4.1.5 on 2023-03-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_squashed_0007_image_last_updated'),
        ('pcbas', '0032_pcba_bom_part_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='generic_files',
            field=models.ManyToManyField(blank=True, to='files.file'),
        ),
    ]
