# Generated by Django 4.2 on 2023-04-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0033_pcba_generic_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='attributes',
            field=models.JSONField(blank=True, default={'Controlled Impedance': False, 'Critical Stackup': False, 'Flex PCB': False}),
        ),
    ]
