# Generated by Django 4.2 on 2023-04-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0034_pcba_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='released_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
