# Generated by Django 4.2 on 2023-04-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0058_part_errata'),
        ('pcbas', '0037_alter_pcba_pcb_layers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='bom_parts',
            field=models.ManyToManyField(blank=True, related_name='parts', to='parts.part'),
        ),
    ]
