# Generated by Django 4.2 on 2023-11-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0038_pcba_bom_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='serial_number_counter',
            field=models.IntegerField(default=0),
        ),
    ]
