# Generated by Django 4.2 on 2023-11-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0039_pcba_serial_number_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='serial_number_offset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pcba',
            name='serial_number_prefix',
            field=models.CharField(default=''),
        ),
    ]
