# Generated by Django 4.2 on 2024-02-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0042_migrate_to_asm_bom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pcba_bom',
        ),
        migrations.RemoveField(
            model_name='pcba',
            name='bom_part_ids',
        ),
        migrations.RemoveField(
            model_name='pcba',
            name='bom_parts',
        ),
        migrations.RemoveField(
            model_name='pcba',
            name='bom_saved',
        ),
        migrations.RemoveField(
            model_name='pcba',
            name='dnm',
        ),
        migrations.RemoveField(
            model_name='pcba',
            name='extra_file1',
        ),
        migrations.RemoveField(
            model_name='pcba',
            name='extra_file2',
        ),
        migrations.RemoveField(
            model_name='pcba',
            name='extra_file3',
        ),
        migrations.RemoveField(
            model_name='pcba',
            name='mpn',
        ),
        migrations.RemoveField(
            model_name='pcba',
            name='nobom',
        ),
        migrations.RemoveField(
            model_name='pcba',
            name='pcba_bom_id',
        ),
        migrations.RemoveField(
            model_name='pcba',
            name='refdes',
        ),
    ]
