# Generated by Django 4.2 on 2024-02-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0043_delete_pcba_bom_remove_pcba_bom_part_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcba',
            name='archived',
        ),
    ]
