# Generated by Django 4.2 on 2024-03-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0047_pcba_currency_pcba_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcba',
            name='errata',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='pcba',
            name='revision_notes',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
