# Generated by Django 4.2.11 on 2024-06-19 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_image_image_compressed copy'),
        ('pcbas', '0049_pcba_markdown_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='gerber_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gerber_file_pcba', to='files.file'),
        ),
    ]
