# Generated by Django 4.2.11 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0055_pcba_markdown_note_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='erp_link',
            field=models.URLField(blank=True, help_text='Link to the part in the external ERP system', max_length=2000, null=True),
        ),
    ]