# Generated by Django 4.2.11 on 2025-11-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0056_increase_revision_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcba',
            name='revision_count_major',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pcba',
            name='revision_count_minor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
