# Generated by Django 4.2.11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pcbas', '0061_pcba_part_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredPcba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pcba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_by', to='pcbas.pcba')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_pcbas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='starredpcba',
            index=models.Index(fields=['user'], name='pcbas_starr_user_idx'),
        ),
        migrations.AddIndex(
            model_name='starredpcba',
            index=models.Index(fields=['pcba'], name='pcbas_starr_pcba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='starredpcba',
            unique_together={('user', 'pcba')},
        ),
    ]
