# Generated by Django 3.0.4 on 2020-06-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='profile_image',
            new_name='image',
        ),
    ]
