# Generated by Django 3.0.4 on 2020-04-27 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField()),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('release_state', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=10)),
                ('revision', models.CharField(max_length=2)),
                ('model_url', models.CharField(blank=True, max_length=200)),
                ('mpn', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=60)),
                ('datasheet', models.CharField(blank=True, max_length=200)),
                ('production_status', models.CharField(blank=True, max_length=20)),
                ('rohs_status_code', models.CharField(blank=True, max_length=20)),
                ('supplier_stock', models.IntegerField(blank=True)),
                ('distributor', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
