# Generated by Django 4.1.5 on 2023-02-10 11:19

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('parts', '0001_initial'), ('parts', '0002_part_internal'), ('parts', '0003_auto_20200428_2002'), ('parts', '0004_auto_20200503_0017'), ('parts', '0005_part_part_type'), ('parts', '0006_auto_20200510_1958'), ('parts', '0007_part_price_qty'), ('parts', '0008_auto_20200527_2003'), ('parts', '0009_auto_20200726_1440'), ('parts', '0010_auto_20200726_1450'), ('parts', '0011_part_last_updated'), ('parts', '0012_auto_20200726_1637'), ('parts', '0009_part_image_link'), ('parts', '0013_merge_20200731_2121'), ('parts', '0014_part_image_link_no'), ('parts', '0015_remove_part_image_link_no'), ('parts', '0013_merge_20200727_0844'), ('parts', '0016_merge_20200801_1406'), ('parts', '0017_auto_20201107_1524'), ('parts', '0018_part_git_link'), ('parts', '0019_part_back_order_quantity'), ('parts', '0020_auto_20210124_1518'), ('parts', '0021_auto_20210220_1629'), ('parts', '0022_auto_20210307_1556'), ('parts', '0023_auto_20210307_1813'), ('parts', '0024_auto_20210307_1826'), ('parts', '0025_auto_20210307_1948'), ('parts', '0026_auto_20210315_2047'), ('parts', '0013_merge_20200727_0835'), ('parts', '0017_merge_20200803_0834'), ('parts', '0018_merge_20201109_0943'), ('parts', '0019_merge_20201116_0850'), ('parts', '0021_merge_20210125_0934'), ('parts', '0022_merge_20210222_0851'), ('parts', '0027_merge_20210327_1301'), ('parts', '0028_auto_20210401_1502'), ('parts', '0029_remove_part_image_link'), ('parts', '0030_part_part_documents'), ('parts', '0031_auto_20210929_1531'), ('parts', '0032_auto_20210929_1615'), ('parts', '0033_part_alternative_parts'), ('parts', '0034_auto_20211103_1605'), ('parts', '0035_auto_20211107_2128'), ('parts', '0036_auto_20211107_2134'), ('parts', '0037_part_archived'), ('parts', '0038_part_revision_notes'), ('parts', '0039_auto_20220128_1611'), ('parts', '0040_auto_20220225_1347'), ('parts', '0041_auto_20220225_1348'), ('parts', '0042_auto_20220225_1357'), ('parts', '0043_auto_20220225_1410'), ('parts', '0044_part_customspecs'), ('parts', '0045_auto_20220408_1328'), ('parts', '0046_part_reference_list_id'), ('parts', '0047_part_unit'), ('parts', '0048_auto_20221103_1742'), ('parts', '0049_part_project'), ('parts', '0050_alter_part_part_number'), ('parts', '0051_alter_part_revision'), ('parts', '0052_part_full_part_number'), ('parts', '0053_part_is_latest_revision'), ('parts', '0054_alter_part_archived_alter_part_datasheet_and_more'), ('parts', '0055_alter_part_distributor')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0020_project_archived_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField(blank=True, default=-1, null=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('release_state', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('revision', models.CharField(blank=True, max_length=2, null=True)),
                ('model_url', models.CharField(blank=True, max_length=500, null=True)),
                ('mpn', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=60, null=True)),
                ('datasheet', models.CharField(blank=True, max_length=200, null=True)),
                ('production_status', models.CharField(blank=True, max_length=20, null=True)),
                ('rohs_status_code', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier_stock', models.IntegerField(blank=True, null=True)),
                ('distributor', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('internal', models.BooleanField(null=True)),
                ('part_type', models.CharField(blank=True, max_length=150, null=True)),
                ('pcb_length', models.CharField(blank=True, max_length=6, null=True)),
                ('pcb_width', models.CharField(blank=True, max_length=6, null=True)),
                ('price_qty', models.CharField(blank=True, max_length=6, null=True)),
                ('farnell_number', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('git_link', models.CharField(blank=True, max_length=200, null=True)),
                ('backorder_quantity', models.IntegerField(blank=True, null=True)),
                ('estimated_factory_lead_days', models.IntegerField(blank=True, null=True)),
                ('on_order_quantity', models.IntegerField(blank=True, null=True)),
                ('sellers', models.TextField(blank=True, max_length=50000, null=True)),
                ('specs', models.TextField(blank=True, max_length=50000, null=True)),
                ('part_file1', models.FileField(blank=True, null=True, upload_to='documents')),
                ('part_file2', models.FileField(blank=True, null=True, upload_to='documents')),
                ('part_file3', models.FileField(blank=True, null=True, upload_to='documents')),
                ('part_file4', models.FileField(blank=True, null=True, upload_to='documents')),
                ('part_file5', models.FileField(blank=True, null=True, upload_to='documents')),
                ('alternative_parts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=[], null=True, size=None)),
                ('archived', models.BooleanField(blank=True, default=False, null=True)),
                ('revision_notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('customSpecs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5000, null=True), blank=True, null=True, size=None)),
                ('reference_list_id', models.IntegerField(blank=True, default=-1)),
                ('unit', models.CharField(blank=True, default='pcs', max_length=20, null=True)),
                ('generic_file_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0), blank=True, default=list, size=None)),
                ('part_drawing', models.IntegerField(blank=True, default=-1)),
                ('part_drawing_raw', models.IntegerField(blank=True, default=-1)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('full_part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_latest_revision', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
