# Generated by Django 3.0.4 on 2020-04-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='internal',
            field=models.BooleanField(null=True),
        ),
    ]
