# Generated by Django 3.0.4 on 2020-04-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_part_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='mpn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
