# Generated by Django 3.0.4 on 2020-05-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_auto_20200428_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='part',
            name='release_state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
