# Generated by Django 3.0.4 on 2020-05-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20200503_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
