# Generated by Django 3.0.4 on 2020-05-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_part_part_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='pcb_length',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='pcb_width',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
