# Generated by Django 3.0.4 on 2020-05-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20200510_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='price_qty',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
