# Generated by Django 3.0.4 on 2020-05-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_part_price_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='pcb_length',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='pcb_width',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
