# Generated by Django 3.0.4 on 2020-07-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_auto_20200527_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='farnellNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
