# Generated by Django 3.0.4 on 2020-07-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_auto_20200726_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='farnellNumber',
            new_name='farnell_number',
        ),
    ]
