# Generated by Django 3.0.4 on 2020-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_auto_20200726_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
