# Generated by Django 3.0.4 on 2020-07-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0012_auto_20200726_1637'),
        ('parts', '0009_part_image_link'),
    ]

    operations = [
    ]
