# Generated by Django 3.0.4 on 2020-08-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0013_merge_20200731_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image_link_no',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
