# Generated by Django 3.0.4 on 2020-08-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0014_part_image_link_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='image_link_no',
        ),
    ]
