# Generated by Django 3.0.4 on 2020-08-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0015_remove_part_image_link_no'),
        ('parts', '0013_merge_20200727_0844'),
    ]

    operations = [
    ]
