# Generated by Django 3.0.4 on 2020-08-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0013_merge_20200727_0835'),
        ('parts', '0016_merge_20200801_1406'),
    ]

    operations = [
    ]
