# Generated by Django 3.0.4 on 2020-11-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0016_merge_20200801_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='image_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
