# Generated by Django 3.0.4 on 2020-11-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_auto_20201107_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='git_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
