# Generated by Django 3.0.4 on 2020-11-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_merge_20200803_0834'),
        ('parts', '0017_auto_20201107_1524'),
    ]

    operations = [
    ]
