# Generated by Django 3.0.4 on 2020-11-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0018_part_git_link'),
        ('parts', '0018_merge_20201109_0943'),
    ]

    operations = [
    ]
