# Generated by Django 3.0.4 on 2021-01-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0018_part_git_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='back_order_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
