# Generated by Django 3.0.4 on 2021-01-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0019_part_back_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='back_order_quantity',
            new_name='backorder_quantity',
        ),
    ]
