# Generated by Django 3.0.4 on 2021-01-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0019_merge_20201116_0850'),
        ('parts', '0020_auto_20210124_1518'),
    ]

    operations = [
    ]
