# Generated by Django 3.0.4 on 2021-02-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0020_auto_20210124_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='attribute_five',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='attribute_four',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='attribute_one',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='attribute_three',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='attribute_two',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
