# Generated by Django 3.0.5 on 2021-02-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0021_merge_20210125_0934'),
        ('parts', '0021_auto_20210220_1629'),
    ]

    operations = [
    ]
