# Generated by Django 3.0.4 on 2021-03-07 17:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0022_auto_20210307_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='digikey_prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='part',
            name='digikey_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='part',
            name='farnell_prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='part',
            name='farnell_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='part',
            name='mouser_prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='part',
            name='mouser_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='part',
            name='rs_online_prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='part',
            name='rs_online_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), default=list, null=True, size=None),
        ),
    ]
