# Generated by Django 3.0.4 on 2021-03-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0023_auto_20210307_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='digikey_prices',
        ),
        migrations.RemoveField(
            model_name='part',
            name='digikey_quantity',
        ),
        migrations.RemoveField(
            model_name='part',
            name='farnell_prices',
        ),
        migrations.RemoveField(
            model_name='part',
            name='farnell_quantity',
        ),
        migrations.RemoveField(
            model_name='part',
            name='mouser_prices',
        ),
        migrations.RemoveField(
            model_name='part',
            name='mouser_quantity',
        ),
        migrations.RemoveField(
            model_name='part',
            name='rs_online_prices',
        ),
        migrations.RemoveField(
            model_name='part',
            name='rs_online_quantity',
        ),
        migrations.AddField(
            model_name='part',
            name='sellers',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='specs',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
