# Generated by Django 3.0.4 on 2021-03-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0025_auto_20210307_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
