# Generated by Django 3.0.4 on 2021-03-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0022_merge_20210222_0851'),
        ('parts', '0026_auto_20210315_2047'),
    ]

    operations = [
    ]
