# Generated by Django 3.0.4 on 2021-04-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0028_auto_20210401_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='image_link',
        ),
    ]
