# Generated by Django 3.0.4 on 2021-09-29 11:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0029_remove_part_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, null=True, upload_to='documents'), blank=True, null=True, size=None),
        ),
    ]
