# Generated by Django 3.0.4 on 2021-09-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0031_auto_20210929_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='part_files',
        ),
        migrations.AddField(
            model_name='part',
            name='part_file1',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_file2',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_file3',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_file4',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_file5',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
