# Generated by Django 3.0.4 on 2021-10-26 15:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0032_auto_20210929_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='alternative_parts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None),
        ),
    ]
