# Generated by Django 3.0.4 on 2021-11-03 15:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0033_part_alternative_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='alternative_parts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
