# Generated by Django 3.0.4 on 2022-01-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0036_auto_20211107_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='archived',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
