# Generated by Django 3.0.4 on 2022-01-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0037_part_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='revision_notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
