# Generated by Django 3.0.4 on 2022-02-25 12:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0041_auto_20220225_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='alternative_parts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=[-1], size=None),
        ),
    ]
