# Generated by Django 3.0.4 on 2022-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0043_auto_20220225_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='customSpecs',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
