# Generated by Django 3.0.4 on 2022-04-08 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0044_part_customspecs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='customSpecs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5000, null=True), blank=True, null=True, size=None),
        ),
    ]
