# Generated by Django 3.2.15 on 2023-01-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0049_part_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
