# Generated by Django 3.2.15 on 2023-01-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0050_alter_part_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='revision',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
