# Generated by Django 3.2.15 on 2023-01-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0051_alter_part_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='full_part_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
