# Generated by Django 4.2 on 2023-04-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0056_part_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='released_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
