# Generated by Django 4.2 on 2023-04-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0057_part_released_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='errata',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
