# Generated by Django 4.2 on 2023-04-29 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
        ('parts', '0058_part_errata'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.supplier'),
        ),
    ]
