# Generated by Django 4.2 on 2023-04-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0060_part_alternative_parts_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='alternative_parts_v2',
            field=models.ManyToManyField(blank=True, to='parts.part'),
        ),
    ]
