# Generated by Django 4.2 on 2023-08-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0061_alter_part_alternative_parts_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='component_vault_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
