# Generated by Django 4.2 on 2023-08-22 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_file_file_alter_image_file'),
        ('parts', '0062_part_component_vault_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image'),
        ),
    ]
