# Generated by Django 4.2 on 2023-08-29 11:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0062_part_component_vault_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_information',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='price_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='part',
            name='stock',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='part',
            name='urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
