# Generated by Django 4.2 on 2023-09-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0063_part_part_information_part_price_history_part_stock_and_more'),
        ('parts', '0063_part_thumbnail'),
    ]

    operations = [
    ]
