# Generated by Django 4.2 on 2023-11-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_file_file_alter_image_file'),
        ('parts', '0064_merge_20230929_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='files',
            field=models.ManyToManyField(blank=True, to='files.file'),
        ),
    ]
