# Generated by Django 4.2 on 2023-11-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0066_migrate_old_part_file_fields_to_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='serial_number_counter',
            field=models.IntegerField(default=0),
        ),
    ]
