# Generated by Django 4.2 on 2023-11-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0067_part_serial_number_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='serial_number_offset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='part',
            name='serial_number_prefix',
            field=models.CharField(default=''),
        ),
    ]
