# Generated by Django 4.2 on 2023-11-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profile_mfa_validated'),
        ('parts', '0068_part_serial_number_offset_part_serial_number_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='quality_assurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile'),
        ),
    ]
