# Generated by Django 4.2 on 2024-02-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0069_part_quality_assurance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='archived',
            new_name='is_archived',
        ),
    ]
