# Generated by Django 4.2 on 2024-03-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0071_rename_part_type_part_part_type_str_parttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.parttype'),
        ),
    ]
