# Generated by Django 4.2 on 2024-03-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0072_part_part_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='icon_url',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
