# Generated by Django 4.2 on 2024-03-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0074_migrate_parttypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='errata',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='revision_notes',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
