# Generated by Django 4.2.11 on 2024-06-07 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0048_markdowntext'),
        ('parts', '0075_alter_part_errata_alter_part_revision_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='markdown_notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.markdowntext'),
        ),
    ]
