# Generated by Django 4.2.11 on 2024-06-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0076_part_markdown_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='prefix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
