# Generated by Django 4.2.11 on 2024-08-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0079_part_current_total_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='minimum_stock_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
