# Generated by Django 4.2.11 on 2024-09-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0080_part_minimum_stock_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_reach_compliant',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='is_rohs_compliant',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='is_ul_compliant',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
