# Generated by Django 4.2.11 on 2024-09-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0081_part_is_reach_compliant_part_is_rohs_compliant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='export_control_classification_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='hs_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
