# Generated by Django 4.2.11 on 2024-10-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0050_document_tags'),
        ('parts', '0084_part_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='markdown_note_tabs',
            field=models.ManyToManyField(blank=True, related_name='parts_markdown_note_tabs', to='documents.markdowntext'),
        ),
    ]
