# Generated by Django 4.2.11 on 2025-10-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0085_part_markdown_note_tabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='revision',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
