# Generated by Django 4.2.11 on 2025-11-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0090_populate_formatted_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='nexar_part_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
