# Generated by Django 4.2.11 on 2025-11-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0091_part_nexar_part_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='source',
            field=models.CharField(blank=True, choices=[('digikey', 'DigiKey'), ('nexar', 'Nexar'), ('manual', 'Manual')], default='manual', help_text='Source of the part data', max_length=20, null=True),
        ),
    ]
