# Generated by Django 4.2.11 on 2025-11-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0092_add_source_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='datasheet',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
