# Generated by Django 4.2.11

from django.db import migrations, models


def set_default_applies_to(apps, schema_editor):
    """Set applies_to='Part' for all existing PartTypes."""
    PartType = apps.get_model('parts', 'PartType')
    PartType.objects.all().update(applies_to='Part')


def reverse_migration(apps, schema_editor):
    """Reverse migration - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0093_alter_part_datasheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='applies_to',
            field=models.CharField(
                choices=[('Part', 'Part'), ('PCBA', 'PCBA'), ('Assembly', 'Assembly')],
                default='Part',
                help_text='Indicates whether this part type applies to Parts, PCBAs, or Assemblies',
                max_length=20
            ),
        ),
        migrations.RunPython(set_default_applies_to, reverse_migration),
    ]
