# Generated by Django 4.2.11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0095_add_default_pcba_asm_part_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_by', to='parts.part')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_parts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='starredpart',
            index=models.Index(fields=['user'], name='parts_starr_user_idx'),
        ),
        migrations.AddIndex(
            model_name='starredpart',
            index=models.Index(fields=['part'], name='parts_starr_part_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='starredpart',
            unique_together={('user', 'part')},
        ),
    ]
