# Generated by Django 4.2.11 on 2026-03-14 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0096_starred_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='sellers',
        ),
        migrations.RemoveField(
            model_name='part',
            name='specs',
        ),
    ]
