# Generated by Django 4.2.11 on 2026-03-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0097_remove_deprecated_sellers_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='naming_convention',
            field=models.TextField(blank=True, help_text='Naming convention rules sent to AI for name suggestions', null=True),
        ),
    ]
