# Generated by Django 4.1.5 on 2023-02-10 11:20

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('projects', '0001_initial'), ('projects', '0002_auto_20200330_0926'), ('projects', '0003_auto_20200331_2225'), ('projects', '0004_remove_project_project_contact'), ('projects', '0005_project_project_contact'), ('projects', '0006_auto_20200410_2313'), ('projects', '0007_auto_20200412_0025'), ('projects', '0008_auto_20200412_0042'), ('projects', '0009_auto_20200412_0044'), ('projects', '0010_auto_20200420_2132'), ('projects', '0011_auto_20200602_1745'), ('projects', '0012_remove_project_document'), ('projects', '0013_auto_20200629_1629'), ('projects', '0014_auto_20200705_1739'), ('projects', '0015_auto_20220601_0902'), ('projects', '0016_auto_20220601_1138'), ('projects', '0017_auto_20220602_1447'), ('projects', '0018_auto_20220616_1143'), ('projects', '0019_project_archived'), ('projects', '0020_project_archived_date'), ('projects', '0021_project_tasks'), ('projects', '0022_auto_20221218_1207'), ('projects', '0023_rename_tasks_task'), ('projects', '0024_remove_project_requiremnt_specification'), ('projects', '0025_remove_project_is_active'), ('projects', '0026_project_is_active'), ('projects', '0027_task_is_active'), ('projects', '0028_task_last_updated'), ('projects', '0029_project_is_archived'), ('projects', '0030_task_dependencies_task_end_time_task_progress_and_more'), ('projects', '0031_rename_end_time_task_end_and_more')]

    initial = True

    dependencies = [
        ('customers', '0002_auto_20200412_0030'),
        ('profiles', '0007_auto_20200602_2130'),
        ('customers', '0001_initial'),
        ('customers', '0007_auto_20210825_1708'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0009_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('project_number', models.IntegerField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile')),
                ('project_assignees', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=[], size=None)),
                ('deadline', models.CharField(blank=True, max_length=20, null=True)),
                ('estimated_work_hours', models.IntegerField(blank=True, null=True)),
                ('start_date', models.CharField(blank=True, max_length=20, null=True)),
                ('archived', models.CharField(blank=True, default='False', max_length=20)),
                ('archived_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_archived', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gantt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('project_id', models.IntegerField(blank=True, default=-1)),
                ('is_billable', models.BooleanField(blank=True, default=False, null=True)),
                ('is_archived', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dependencies', models.ManyToManyField(blank=True, to='projects.task')),
                ('end', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(blank=True, default=0)),
                ('start', models.DateField(blank=True, null=True)),
                ('gantt_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.gantt')),
            ],
        ),
    ]
