# Generated by Django 3.0.4 on 2020-03-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200330_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='requiremnt_specification',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
