# Generated by Django 3.0.4 on 2020-03-31 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200331_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_contact',
        ),
    ]
