# Generated by Django 3.0.4 on 2020-04-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200412_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
