# Generated by Django 3.0.4 on 2020-06-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200420_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdocument',
            name='author',
        ),
        migrations.DeleteModel(
            name='ProjectDocumentType',
        ),
        migrations.DeleteModel(
            name='ProjectDocument',
        ),
    ]
