# Generated by Django 3.0.4 on 2020-06-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200602_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
    ]
