# Generated by Django 3.0.4 on 2020-06-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
