# Generated by Django 3.0.4 on 2020-07-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200602_2130'),
        ('projects', '0013_auto_20200629_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Profile'),
        ),
    ]
