# Generated by Django 3.0.4 on 2022-06-01 11:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20220601_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_assignees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.IntegerField(blank=True),
        ),
    ]
