# Generated by Django 3.0.4 on 2022-06-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20220601_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_work_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
