# Generated by Django 3.0.4 on 2022-06-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20220616_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archived',
            field=models.CharField(blank=True, default='False', max_length=20),
        ),
    ]
