# Generated by Django 3.0.4 on 2022-06-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archived_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
