# Generated by Django 3.2.15 on 2022-12-10 16:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_archived_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, default=[], size=None),
        ),
    ]
