# Generated by Django 3.2.15 on 2022-12-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_project_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('project_id', models.IntegerField(blank=True, default=-1)),
                ('is_billable', models.BooleanField(blank=True, default=False, null=True)),
                ('is_archived', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='tasks',
        ),
    ]
