# Generated by Django 3.2.15 on 2022-12-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_rename_tasks_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='requiremnt_specification',
        ),
    ]
