# Generated by Django 4.1.5 on 2023-02-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_project_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='projects.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Gantt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='gantt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.gantt'),
        ),
    ]
