# Generated by Django 4.1.5 on 2023-02-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_task_dependencies_task_end_time_task_progress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start_time',
            new_name='start',
        ),
    ]
