# Generated by Django 4.1.5 on 2023-02-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_squashed_0031_rename_end_time_task_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantt',
            name='view_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
