# Generated by Django 4.2 on 2024-02-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_add_users_to_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='archived',
        ),
    ]
