# Generated by Django 4.2.11 on 2024-05-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_alter_project_description_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workload_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
