# Generated by Django 4.2.11 on 2024-08-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_task_workload_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
