# Generated by Django 4.2.11 on 2024-08-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20240822_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
