# Generated by Django 4.2.11 on 2024-09-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_project_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notify_project_owner_on_issue_close',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='notify_project_owner_on_issue_creation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='notify_project_owner_on_item_new_revision',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='notify_project_owner_on_item_passed_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='notify_project_owner_on_item_released',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='notify_project_owner_on_item_state_change_to_review',
            field=models.BooleanField(default=True),
        ),
    ]
