# Generated by Django 4.2.11 on 2024-09-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='task_tags', to='projects.tag'),
        ),
    ]
