# Generated by Django 4.2.11 on 2025-11-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_project_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_project_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
