# Generated by Django 4.2.11 on 2025-11-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_populate_full_project_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
