# Generated by Django 4.2.11 on 2025-11-23 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0041_create_workflows'),
        ('projects', '0054_alter_project_project_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger_type', models.CharField(choices=[('pcba_created', 'PCBA Created'), ('part_created', 'Part Created'), ('assembly_created', 'Assembly Created'), ('document_created', 'Document Created'), ('revision_created', 'Revision Created')], help_text='Event type that triggers this workflow', max_length=50)),
                ('trigger_entity_type', models.CharField(choices=[('pcbas', 'PCBAs'), ('parts', 'Parts'), ('assemblies', 'Assemblies'), ('documents', 'Documents'), ('all', 'All')], default='all', help_text='Entity type filter for the trigger', max_length=50)),
                ('scope_type', models.CharField(choices=[('organization', 'Organization-wide'), ('project', 'Project-specific')], help_text='Whether this workflow applies organization-wide or to a specific project', max_length=20)),
                ('is_enabled', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization for organization-wide workflows', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Project for project-specific workflows', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_issue', 'Create Issue')], help_text='Type of action to execute', max_length=50)),
                ('action_config', models.JSONField(blank=True, default=dict, help_text='Configuration data for the action (e.g., issue template, title, criticality)')),
                ('order', models.IntegerField(default=0, help_text='Execution order for multiple actions')),
                ('is_enabled', models.BooleanField(blank=True, default=True, help_text='Enable/disable this specific action')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='projects.workflow')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['workflow', 'order'], name='projects_wo_workflo_a78499_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['trigger_type'], name='projects_wo_trigger_5a0977_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['scope_type'], name='projects_wo_scope_t_d8bbb5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['organization'], name='projects_wo_organiz_326f66_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['project'], name='projects_wo_project_fc1d07_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['is_enabled'], name='projects_wo_is_enab_840905_idx'),
        ),
    ]
