# Generated by Django 4.2.11 on 2025-11-23 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0055_create_workflows'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='created_by_workflow',
            field=models.ForeignKey(blank=True, help_text='Workflow that created this issue (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to='projects.workflow'),
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(help_text='Type of trigger that caused this execution', max_length=50)),
                ('entity_type', models.CharField(help_text='Type of entity that triggered the workflow', max_length=50)),
                ('entity_id', models.IntegerField(help_text='ID of the entity that triggered the workflow')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='success', help_text='Overall status of the workflow execution', max_length=20)),
                ('executed_at', models.DateTimeField(auto_now_add=True, help_text='When the workflow was executed')),
                ('actions_executed', models.JSONField(blank=True, default=list, help_text='List of actions that were executed and their results')),
                ('errors', models.JSONField(blank=True, default=list, help_text='List of any errors that occurred during execution')),
                ('executed_by', models.ForeignKey(blank=True, help_text='User who triggered the event (not necessarily the workflow creator)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_executions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, help_text='The workflow that was executed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='projects.workflow')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('viewed', 'Viewed'), ('enabled', 'Enabled'), ('disabled', 'Disabled')], help_text='Type of action performed', max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Details of what changed (field name -> old value, new value)')),
                ('workflow_name', models.CharField(blank=True, help_text='Name of workflow at time of action (for deleted workflows)', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user (if available)', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string (if available)')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, help_text='The workflow that was changed (null if deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='projects.workflow')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='issues',
            name='workflow_execution',
            field=models.ForeignKey(blank=True, help_text='Workflow execution record that created this issue (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to='projects.workflowexecution'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['workflow', '-executed_at'], name='projects_wo_workflo_cfe754_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['entity_type', 'entity_id'], name='projects_wo_entity__7da84d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['trigger_type', '-executed_at'], name='projects_wo_trigger_b67e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['status'], name='projects_wo_status_075dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowauditlog',
            index=models.Index(fields=['workflow', '-performed_at'], name='wf_audit_workflow_perf_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowauditlog',
            index=models.Index(fields=['action', '-performed_at'], name='wf_audit_action_perf_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowauditlog',
            index=models.Index(fields=['performed_by', '-performed_at'], name='wf_audit_performed_by_idx'),
        ),
    ]
