# Generated by Django 4.1.5 on 2023-02-10 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('customers', '0001_initial'), ('customers', '0002_auto_20200412_0030'), ('customers', '0003_auto_20200629_1629'), ('customers', '0004_auto_20201206_2216'), ('customers', '0005_auto_20210825_1705'), ('customers', '0006_auto_20210825_1706'), ('customers', '0007_auto_20210825_1708'), ('customers', '0008_remove_customer_is_active'), ('customers', '0009_customer_is_active'), ('customers', '0010_customer_is_archived'), ('customers', '0011_alter_customer_contact_phone_number'), ('customers', '0012_alter_customer_name')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=75, null=True)),
                ('contact_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('customer_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('favorite_project', models.CharField(blank=True, max_length=3, null=True)),
                ('favorite_task', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_archived', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
