# Generated by Django 3.0.4 on 2020-06-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200412_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
