# Generated by Django 3.0.4 on 2021-08-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20210825_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
