# Generated by Django 3.2.15 on 2023-01-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customer_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
