name: Build and deploy Mkdocs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build

      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages:gh-pages

      - name: Deploy MkDocs site
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy
