# Generated by Django 4.1.5 on 2023-02-10 11:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('assembly_bom', '0001_initial'), ('assembly_bom', '0002_auto_20220324_1257'), ('assembly_bom', '0003_assembly_bom_bom_name'), ('assembly_bom', '0004_auto_20220411_1432'), ('assembly_bom', '0005_auto_20220412_0924'), ('assembly_bom', '0006_assembly_bom_mpn_refdes_asm'), ('assembly_bom', '0007_auto_20220510_0836'), ('assembly_bom', '0008_assembly_bom_comments')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly_bom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcba_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('part_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('asm_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('assembly_id', models.IntegerField(blank=True, null=True)),
                ('asm_bom_part_number', models.IntegerField(blank=True, null=True)),
                ('asm_bom_revision', models.CharField(blank=True, max_length=20, null=True)),
                ('bom_name', models.TextField(blank=True, max_length=50, null=True)),
                ('mpn_fn_part', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None)),
                ('mpn_fn_pcba', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None)),
                ('mpn_fn_asm', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
