# Generated by Django 3.0.4 on 2022-03-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly_bom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_bom',
            name='asm_bom_part_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assembly_bom',
            name='asm_bom_revision',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
