# Generated by Django 3.0.4 on 2022-04-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly_bom', '0003_assembly_bom_bom_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assembly_bom',
            old_name='asm_bom_id',
            new_name='assembly_id',
        ),
    ]
