# Generated by Django 3.0.4 on 2022-04-12 11:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly_bom', '0005_auto_20220412_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_bom',
            name='mpn_refdes_asm',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
    ]
