# Generated by Django 3.0.4 on 2022-05-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly_bom', '0006_assembly_bom_mpn_refdes_asm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assembly_bom',
            old_name='mpn_refdes_asm',
            new_name='mpn_fn_asm',
        ),
        migrations.RenameField(
            model_name='assembly_bom',
            old_name='mpn_refdes_part',
            new_name='mpn_fn_part',
        ),
        migrations.RenameField(
            model_name='assembly_bom',
            old_name='mpn_refdes_pcba',
            new_name='mpn_fn_pcba',
        ),
    ]
