# Generated by Django 3.0.4 on 2022-05-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly_bom', '0007_auto_20220510_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_bom',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
