# Generated by Django 4.2 on 2023-04-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0058_part_errata'),
        ('assemblies', '0035_assembly_released_date'),
        ('pcbas', '0038_pcba_bom_parts'),
        ('assembly_bom', '0001_squashed_0008_assembly_bom_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_bom',
            name='bom_asms',
            field=models.ManyToManyField(blank=True, related_name='bom_asms', to='assemblies.assembly'),
        ),
        migrations.AddField(
            model_name='assembly_bom',
            name='bom_parts',
            field=models.ManyToManyField(blank=True, related_name='bom_parts', to='parts.part'),
        ),
        migrations.AddField(
            model_name='assembly_bom',
            name='bom_pcbas',
            field=models.ManyToManyField(blank=True, related_name='bom_pcbas', to='pcbas.pcba'),
        ),
    ]
