# Generated by Django 4.2 on 2023-11-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0041_pcba_quality_assurance'),
        ('assemblies', '0040_assembly_quality_assurance'),
        ('parts', '0069_part_quality_assurance'),
        ('assembly_bom', '0009_assembly_bom_bom_asms_assembly_bom_bom_parts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designator', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('is_mounted', models.BooleanField(blank=True, default=False)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_item', to='assemblies.assembly')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_item', to='parts.part')),
                ('pcba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_item', to='pcbas.pcba')),
            ],
        ),
    ]
