# Generated by Django 4.2 on 2023-11-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly_bom', '0009_assembly_bom_bom_asms_assembly_bom_bom_parts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_bom',
            name='bom_content',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
