# Generated by Django 4.2 on 2023-11-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly_bom', '0010_bom_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom_item',
            name='is_mounted',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
