# Generated by Django 4.2 on 2023-11-25 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0069_part_quality_assurance'),
        ('assemblies', '0040_assembly_quality_assurance'),
        ('pcbas', '0041_pcba_quality_assurance'),
        ('assembly_bom', '0011_alter_bom_item_is_mounted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom_item',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assembly_bom.assembly_bom'),
        ),
        migrations.AlterField(
            model_name='bom_item',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_item', to='assemblies.assembly'),
        ),
        migrations.AlterField(
            model_name='bom_item',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_item', to='parts.part'),
        ),
        migrations.AlterField(
            model_name='bom_item',
            name='pcba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_item', to='pcbas.pcba'),
        ),
    ]
