# Generated by Django 4.2 on 2023-11-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly_bom', '0012_bom_item_bom_alter_bom_item_assembly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom_item',
            name='quantity',
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
