# Generated by Django 4.2 on 2023-11-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly_bom', '0010_assembly_bom_bom_content'),
        ('assembly_bom', '0013_alter_bom_item_quantity'),
    ]

    operations = [
    ]
