# Generated by Django 4.2 on 2023-11-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly_bom', '0014_merge_20231125_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly_bom',
            name='bom_content',
        ),
    ]
