# Generated by Django 4.2 on 2024-02-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly_bom', '0016_migrate_to_bom_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom_item',
            name='temporary_manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bom_item',
            name='temporary_mpn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
