# Generated by Django 4.2 on 2024-02-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly_bom', '0017_bom_item_temporary_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom_item',
            name='designator',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
