# Generated by Django 4.2 on 2024-02-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcbas', '0041_pcba_quality_assurance'),
        ('assembly_bom', '0018_alter_bom_item_designator'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_bom',
            name='pcba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbas.pcba'),
        ),
    ]
