# Generated by Django 4.2 on 2024-02-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly_bom', '0019_assembly_bom_pcba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly_bom',
            name='asm_bom_part_number',
        ),
        migrations.RemoveField(
            model_name='assembly_bom',
            name='asm_bom_revision',
        ),
        migrations.RemoveField(
            model_name='assembly_bom',
            name='asm_ids',
        ),
        migrations.RemoveField(
            model_name='assembly_bom',
            name='bom_asms',
        ),
        migrations.RemoveField(
            model_name='assembly_bom',
            name='bom_parts',
        ),
        migrations.RemoveField(
            model_name='assembly_bom',
            name='bom_pcbas',
        ),
        migrations.RemoveField(
            model_name='assembly_bom',
            name='mpn_fn_asm',
        ),
        migrations.RemoveField(
            model_name='assembly_bom',
            name='mpn_fn_part',
        ),
        migrations.RemoveField(
            model_name='assembly_bom',
            name='mpn_fn_pcba',
        ),
        migrations.RemoveField(
            model_name='assembly_bom',
            name='part_ids',
        ),
        migrations.RemoveField(
            model_name='assembly_bom',
            name='pcba_ids',
        ),
    ]
